[package]
publish = false
name = "shiro-rs-node"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
repository.workspace = true
description = "Native Node.js bindings for shiro-rs"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
rand = { version = "0.10.3", default-features = false }
shiro-rs = { path = "../shiro-rs", version = "0.1.0" }
napi = { version = "3.14", default-features = false, features = ["napi8"] }
napi-derive = "3.6"

serde_json = "1.0.151"

[build-dependencies]
napi-build = "2.6"
