/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class AlignmentOptions {
  close(): void
  free(): void
  get is_closed(): boolean
  get duration_mode(): number
  set duration_mode(value: number)
  get isolated(): boolean
  set isolated(value: boolean)
  get hsmm_temperature(): number
  set hsmm_temperature(value: number)
  get duration_weight(): number
  set duration_weight(value: number)
  get state_radius(): number
  set state_radius(value: number)
  get duration_extra(): number
  set duration_extra(value: number)
  get duration_extra_factor(): number
  set duration_extra_factor(value: number)
  get geometric_temperature(): number
  set geometric_temperature(value: number)
  get pruning_slope(): number
  set pruning_slope(value: number)
  constructor()
  cloned(): AlignmentOptions
}

export declare class Assignment {
  close(): void
  free(): void
  get is_closed(): boolean
  get state(): number
  set state(value: number)
  get file(): number
  set file(value: number)
  get segment(): number
  set segment(value: number)
  constructor(state: number, file: number, segment: number)
  cloned(): Assignment
}

export declare class Assignments {
  close(): void
  free(): void
  get is_closed(): boolean
  constructor()
  get length(): number
  get(index: number): Assignment | null
  push(value: Assignment): void
  replace(index: number, value: Assignment): void
  clear(): void
  cloned(): Assignments
}

export declare class Audio {
  close(): void
  free(): void
  get is_closed(): boolean
  constructor(sampleRate: number, samples: Float32Array)
  get sample_rate(): number
  set sample_rate(value: number)
  samples(): Float32Array
  set_samples(samples: Float32Array): void
  cloned(): Audio
  static prepare_with_sequence(wave: Wave, options: AudioOptions, sequence: DitherSequence): Audio
  static prepare(wave: Wave, options: AudioOptions, uniform: () => number): Audio
}

export declare class AudioOptions {
  close(): void
  free(): void
  get is_closed(): boolean
  get normalize(): boolean
  set normalize(value: boolean)
  get dither_level(): number
  set dither_level(value: number)
  get output_sample_rate(): number | null
  set output_sample_rate(value: number | undefined | null)
  get boundary(): number
  set boundary(value: number)
  get kernel(): number
  set kernel(value: number)
  constructor()
  cloned(): AudioOptions
}

export declare class BatchExtraction {
  close(): void
  free(): void
  get is_closed(): boolean
  constructor(audio: Audio, features: Features, outputs: BatchOutputs)
  audio(): Audio
  set_audio(value: Audio): void
  features(): Features
  set_features(value: Features): void
  outputs(): BatchOutputs
  set_outputs(value: BatchOutputs): void
  cloned(): BatchExtraction
  static extract_with_sequence(wave: Wave, stem: string, options: BatchOptions, value: number, sequence: DitherSequence): BatchExtraction
  static extract(wave: Wave, stem: string, options: BatchOptions, value: number, uniform: () => number): BatchExtraction
}

export declare class BatchOptions {
  close(): void
  free(): void
  get is_closed(): boolean
  constructor()
  audio(): AudioOptions
  set_audio(value: AudioOptions): void
  get input_extension(): string
  set input_extension(value: string)
  cloned(): BatchOptions
}

export declare class BatchOutputs {
  close(): void
  free(): void
  get is_closed(): boolean
  get raw(): string
  set raw(value: string)
  get parameters(): string
  set parameters(value: string)
  get mfcc(): string | null
  set mfcc(value: string | undefined | null)
  constructor(raw: string, parameters: string, mfcc?: string | undefined | null)
  cloned(): BatchOutputs
}

export declare class Dataset {
  close(): void
  free(): void
  get is_closed(): boolean
  constructor()
  observations(): Observations
  segmentations(): Segmentations
  set_observations(values: Observations): void
  set_segmentations(values: Segmentations): void
  replace(observations: Observations, segmentations: Segmentations): void
  cloned(): Dataset
  static load_files(document: SegmentationDocument, model: Model, maximumFrames: number): Dataset
  static load(document: SegmentationDocument, model: Model, files: FeatureFiles, maximumFrames: number): Dataset
}

export declare class Datasets {
  static load_training_paths(document: SegmentationDocument, model: Model, maximumFrames: number, isolated: boolean): Datasets
  close(): void
  free(): void
  get is_closed(): boolean
  constructor()
  get length(): number
  get(index: number): Dataset | null
  push(value: Dataset): void
  replace(index: number, value: Dataset): void
  clear(): void
  cloned(): Datasets
  static load_training_files(document: SegmentationDocument, model: Model, files: FeatureFiles, maximumFrames: number, isolated: boolean): Datasets
}

export declare class DecodedModel {
  close(): void
  free(): void
  get is_closed(): boolean
  get position(): bigint
  parameters(): Model
  into_parameters(): Model
}

export declare class DitherSequence {
  close(): void
  free(): void
  get is_closed(): boolean
  static windows(): DitherSequence
  static linux_gnu(): DitherSequence
  next_uniform(): number
}

export declare class Duration {
  close(): void
  free(): void
  get is_closed(): boolean
  constructor()
  values(): Float32Array
  constraints(): Int32Array
  set_values(values: Float32Array): void
  set_constraints(values: Int32Array): void
  cloned(): Duration
}

export declare class Durations {
  close(): void
  free(): void
  get is_closed(): boolean
  constructor()
  get length(): number
  get(index: number): Duration | null
  push(value: Duration): void
  replace(index: number, value: Duration): void
  clear(): void
  cloned(): Durations
}

export declare class Extractor {
  close(): void
  free(): void
  get is_closed(): boolean
  static native(preset: number): Extractor
  static sptk(programs: SptkPrograms): Extractor
  static lua(interpreter: string, script: string, executableDirectory: string): Extractor
  cloned(): Extractor
}

export declare class FeatureFiles {
  close(): void
  free(): void
  get is_closed(): boolean
  constructor()
  get length(): number
  names(): Array<string>
  get(filename: string): Uint8Array | null
  set(filename: string, bytes: Uint8Array): void
  remove(filename: string): boolean
  clear(): void
  cloned(): FeatureFiles
}

export declare class FeatureOptions {
  close(): void
  free(): void
  get is_closed(): boolean
  get kind(): number
  set kind(value: number)
  get order(): number
  set order(value: number)
  get channels(): number
  set channels(value: number)
  get frame_length(): number
  set frame_length(value: number)
  get hop(): number
  set hop(value: number)
  get sample_rate_hz(): number
  set sample_rate_hz(value: number)
  get minimum_bandwidth_hz(): number
  set minimum_bandwidth_hz(value: number)
  get warp(): number
  set warp(value: number)
  get include_dc(): boolean
  set include_dc(value: boolean)
  get energy(): number
  set energy(value: number)
  get delta(): boolean
  set delta(value: boolean)
  get acceleration(): boolean
  set acceleration(value: boolean)
  constructor()
  cloned(): FeatureOptions
}

export declare class Features {
  close(): void
  free(): void
  get is_closed(): boolean
  constructor(frames: number, columns: number, values: Float32Array)
  static extract(signal: Float32Array, options: FeatureOptions): Features
  get frames(): number
  set frames(value: number)
  get columns(): number
  set columns(value: number)
  values(): Float32Array
  set_values(values: Float32Array): void
  cloned(): Features
}

export declare class FileLikelihoods {
  close(): void
  free(): void
  get is_closed(): boolean
  constructor(values: Float32Array)
  values(): Float32Array
  replace(values: Float32Array): void
  cloned(): FileLikelihoods
}

export declare class Gaussian {
  close(): void
  free(): void
  get is_closed(): boolean
  constructor(components: number, dimensions: number)
  get dimensions(): number
  get components(): number
  weights(): Float32Array
  means(): Float32Array
  variances(): Float32Array
  variance_floors(): Float32Array
  replace(dimensions: number, weights: Float32Array, means: Float32Array, variances: Float32Array, varianceFloors: Float32Array): void
  cloned(): Gaussian
}

export declare class Gaussians {
  close(): void
  free(): void
  get is_closed(): boolean
  constructor()
  get length(): number
  get(index: number): Gaussian | null
  push(value: Gaussian): void
  replace(index: number, value: Gaussian): void
  clear(): void
  cloned(): Gaussians
}

export declare class IndexEntries {
  close(): void
  free(): void
  get is_closed(): boolean
  constructor()
  get length(): number
  get(index: number): IndexEntry | null
  push(value: IndexEntry): void
  replace(index: number, value: IndexEntry): void
  clear(): void
  cloned(): IndexEntries
  static read(bytes: Uint8Array, directory: string, leftJson: string, rightJson: string): IndexEntries
}

export declare class IndexEntry {
  close(): void
  free(): void
  get is_closed(): boolean
  constructor(stem: string, phonemesJson: string)
  get stem(): string
  set stem(stem: string)
  phonemes_json(): string
  set_phonemes_json(json: string): void
  cloned(): IndexEntry
}

export declare class InitializationOptions {
  close(): void
  free(): void
  get is_closed(): boolean
  get flat_start(): boolean
  set flat_start(value: boolean)
  get globally_tied(): boolean
  set globally_tied(value: boolean)
  get variance_floor_ratio(): number
  set variance_floor_ratio(value: number)
  constructor()
  cloned(): InitializationOptions
}

export declare class IsolatedGroup {
  close(): void
  free(): void
  get is_closed(): boolean
  constructor(firstState: number, firstFrame: number, observation: Observation, states: States)
  get first_state(): number
  set first_state(value: number)
  get first_frame(): number
  set first_frame(value: number)
  observation(): Observation
  set_observation(value: Observation): void
  states(): States
  set_states(value: States): void
  cloned(): IsolatedGroup
}

export declare class IsolatedGroups {
  close(): void
  free(): void
  get is_closed(): boolean
  constructor()
  get length(): number
  get(index: number): IsolatedGroup | null
  push(value: IsolatedGroup): void
  replace(index: number, value: IsolatedGroup): void
  clear(): void
  cloned(): IsolatedGroups
  static split(model: Model, observation: Observation, states: States): IsolatedGroups
}

export declare class IterationReport {
  close(): void
  free(): void
  get is_closed(): boolean
  constructor(iteration: number, temperature: number, meanLogLikelihood: number, rows: LikelihoodRows)
  get iteration(): number
  set iteration(value: number)
  get temperature(): number
  set temperature(value: number)
  get mean_log_likelihood(): number
  set mean_log_likelihood(value: number)
  file_likelihoods(): LikelihoodRows
  set_file_likelihoods(rows: LikelihoodRows): void
  cloned(): IterationReport
}

export declare class IterationReports {
  close(): void
  free(): void
  get is_closed(): boolean
  constructor()
  get length(): number
  get(index: number): IterationReport | null
  push(value: IterationReport): void
  replace(index: number, value: IterationReport): void
  clear(): void
  cloned(): IterationReports
}

export declare class JumpGroup {
  close(): void
  free(): void
  get is_closed(): boolean
  constructor(deltas: Int32Array, probabilities: Float32Array)
  get length(): number
  deltas(): Int32Array
  probabilities(): Float32Array
  cloned(): JumpGroup
}

export declare class Label {
  close(): void
  free(): void
  get is_closed(): boolean
  get start(): number
  set start(value: number)
  get end(): number
  set end(value: number)
  constructor(start: number, end: number, name: string)
  get name(): string
  set name(name: string)
  cloned(): Label
}

export declare class Labels {
  close(): void
  free(): void
  get is_closed(): boolean
  constructor()
  static parse(text: string): Labels
  get length(): number
  get(index: number): Label | null
  push(label: Label): void
  replace(index: number, label: Label): void
  clear(): void
  cloned(): Labels
  write(): Uint8Array
  to_states(map: PhoneMap, hop: number): States
  static from_states(states: States, hop: number, includeStates: boolean): Labels
}

export declare class LikelihoodRows {
  close(): void
  free(): void
  get is_closed(): boolean
  constructor()
  get length(): number
  get(index: number): FileLikelihoods | null
  push(value: FileLikelihoods): void
  replace(index: number, value: FileLikelihoods): void
  clear(): void
  cloned(): LikelihoodRows
}

export declare class Model {
  align_states(observation: Observation, states: States, options: AlignmentOptions): States
  align_document(document: SegmentationDocument, files: FeatureFiles, maximumFrames: number, options: AlignmentOptions): SegmentationDocument
  static read_file(path: string): Model
  write_file(path: string, encoding: number): void
  align_document_files(document: SegmentationDocument, options: AlignmentOptions): SegmentationDocument
  initialize(dataset: Dataset, options: InitializationOptions): Model
  close(): void
  free(): void
  get is_closed(): boolean
  constructor()
  get streams(): number
  get durations(): number
  stream(index: number): Stream | null
  duration(index: number): Duration | null
  set_stream(index: number, value: Stream): void
  set_duration(index: number, value: Duration): void
  replace(streams: Streams, durations: Durations): void
  cloned(): Model
  validate(): void
  dimensions(): Uint32Array
  static read(bytes: Uint8Array): Model
  static read_with_limits(bytes: Uint8Array, maxArrayEntries: number): Model
  static read_prefix(bytes: Uint8Array): DecodedModel
  static read_prefix_with_limits(bytes: Uint8Array, maxArrayEntries: number): DecodedModel
  write(): Uint8Array
  write_with_encoding(code: number): Uint8Array
  train(files: Datasets, options: TrainingOptions): TrainingResult
  train_with_progress(files: Datasets, options: TrainingOptions, progress: (report: IterationReport) => void): TrainingResult
  untie(document: SegmentationDocument): UntiedModel
}

export declare class ModelDefinition {
  close(): void
  free(): void
  get is_closed(): boolean
  constructor(json: string)
  json(): string
  replace(json: string): void
  cloned(): ModelDefinition
  build(): Model
}

export declare class Observation {
  close(): void
  free(): void
  get is_closed(): boolean
  constructor(frames: number, dimensions: Uint32Array)
  static read_rawfloat(bytes: Uint8Array, dimensions: Uint32Array, maximumFrames: number): Observation
  static from_model_rawfloat(bytes: Uint8Array, model: Model, maximumFrames: number): Observation
  get frames(): number
  get streams(): number
  stream(index: number): ObservationStream | null
  set_stream(index: number, value: ObservationStream): void
  replace(frames: number, streams: ObservationStreams): void
  frame(stream: number, time: number): Float32Array | null
  validate(): void
  cloned(): Observation
  write(): Uint8Array
}

export declare class Observations {
  close(): void
  free(): void
  get is_closed(): boolean
  constructor()
  get length(): number
  get(index: number): Observation | null
  push(value: Observation): void
  replace(index: number, value: Observation): void
  clear(): void
  cloned(): Observations
}

export declare class ObservationStream {
  close(): void
  free(): void
  get is_closed(): boolean
  constructor(dimensions: number, values: Float32Array)
  get dimensions(): number
  values(): Float32Array
  replace(dimensions: number, values: Float32Array): void
  cloned(): ObservationStream
}

export declare class ObservationStreams {
  close(): void
  free(): void
  get is_closed(): boolean
  constructor()
  get length(): number
  get(index: number): ObservationStream | null
  push(value: ObservationStream): void
  replace(index: number, value: ObservationStream): void
  clear(): void
  cloned(): ObservationStreams
}

export declare class PhoneMap {
  close(): void
  free(): void
  get is_closed(): boolean
  constructor(json: string)
  json(): string
  replace(json: string): void
  cloned(): PhoneMap
  static create(text: string, options: PhoneMapOptions): PhoneMap
  to_definition(dimensions: number, hop: number): ModelDefinition
  initial(phones: Array<string>, frames: number): States
}

export declare class PhoneMapOptions {
  close(): void
  free(): void
  get is_closed(): boolean
  get states_per_phone(): number
  set states_per_phone(value: number)
  get streams(): number
  set streams(value: number)
  get topology(): string | null
  set topology(value: string | undefined | null)
  get weak_skips(): boolean
  set weak_skips(value: boolean)
  constructor()
  cloned(): PhoneMapOptions
}

export declare class Segmentation {
  close(): void
  free(): void
  get is_closed(): boolean
  constructor(streams: number, segments: number)
  static from_states(states: States, model: Model): Segmentation
  get streams(): number
  get segments(): number
  boundaries(): Int32Array
  duration_states(): Int32Array
  output_states(stream: number): Int32Array
  set_boundaries(values: Int32Array): void
  set_duration_states(values: Int32Array): void
  set_output_states(stream: number, values: Int32Array): void
  outgoing(state: number): JumpGroup | null
  set_outgoing(state: number, jumps: JumpGroup): void
  replace(value: Segmentation): void
  validate(): void
  cloned(): Segmentation
  write(): Uint8Array
}

export declare class SegmentationDocument {
  close(): void
  free(): void
  get is_closed(): boolean
  constructor(json: string)
  json(): string
  replace(json: string): void
  cloned(): SegmentationDocument
}

export declare class Segmentations {
  close(): void
  free(): void
  get is_closed(): boolean
  constructor()
  get length(): number
  get(index: number): Segmentation | null
  push(value: Segmentation): void
  replace(index: number, value: Segmentation): void
  clear(): void
  cloned(): Segmentations
}

export declare class SegmentedUtterances {
  close(): void
  free(): void
  get is_closed(): boolean
  constructor(model: Model, phonemap: PhoneMap, definition: ModelDefinition, initialSegmentation: SegmentationDocument, alignment: SegmentationDocument)
  static split_features(features: Features, filename: string, options: UtteranceOptions, source: UtteranceModelSource): SegmentedUtterances
  cloned(): SegmentedUtterances
  phones_json(): string
  set_phones_json(json: string): void
  uninitialized_model(): Model | null
  set_uninitialized_model(value: Model): void
  clear_uninitialized_model(): void
  initialized_model(): Model | null
  set_initialized_model(value: Model): void
  clear_initialized_model(): void
  phonemap(): PhoneMap
  set_phonemap(value: PhoneMap): void
  definition(): ModelDefinition
  set_definition(value: ModelDefinition): void
  initial_segmentation(): SegmentationDocument
  set_initial_segmentation(value: SegmentationDocument): void
  model(): Model
  set_model(value: Model): void
  iterations(): IterationReports
  set_iterations(value: IterationReports): void
  alignment(): SegmentationDocument
  set_alignment(value: SegmentationDocument): void
  labels(): Labels
  set_labels(value: Labels): void
}

export declare class SegmentedWave {
  close(): void
  free(): void
  get is_closed(): boolean
  constructor(audio: Audio, features: Features, utterances: SegmentedUtterances)
  static split_with_sequence(wave: Wave, filename: string, dimensions: number, kind: number, options: UtteranceOptions, source: UtteranceModelSource, sequence: DitherSequence): SegmentedWave
  static split(wave: Wave, filename: string, dimensions: number, kind: number, options: UtteranceOptions, source: UtteranceModelSource, uniform: () => number): SegmentedWave
  cloned(): SegmentedWave
  audio(): Audio
  set_audio(value: Audio): void
  features(): Features
  set_features(value: Features): void
  utterances(): SegmentedUtterances
  set_utterances(value: SegmentedUtterances): void
}

export declare class SptkPrograms {
  close(): void
  free(): void
  get is_closed(): boolean
  get frame(): string
  set frame(value: string)
  get mfcc(): string
  set mfcc(value: string)
  get delta(): string
  set delta(value: string)
  constructor()
}

export declare class States {
  close(): void
  free(): void
  get is_closed(): boolean
  constructor(json: string)
  json(): string
  replace(json: string): void
  cloned(): States
}

export declare class Stream {
  close(): void
  free(): void
  get is_closed(): boolean
  constructor(emissions: number, components: number, dimensions: number)
  get emissions(): number
  weight(): Float32Array
  set_weight(values: Float32Array): void
  emission(index: number): Gaussian | null
  set_emission(index: number, value: Gaussian): void
  replace(weight: Float32Array, emissions: Gaussians): void
  cloned(): Stream
}

export declare class Streams {
  close(): void
  free(): void
  get is_closed(): boolean
  constructor()
  get length(): number
  get(index: number): Stream | null
  push(value: Stream): void
  replace(index: number, value: Stream): void
  clear(): void
  cloned(): Streams
}

export declare class TrainingOptions {
  close(): void
  free(): void
  get is_closed(): boolean
  get iterations(): number
  set iterations(value: number)
  get duration_mode(): number
  set duration_mode(value: number)
  get hsmm_temperature(): number
  set hsmm_temperature(value: number)
  get duration_weight(): number
  set duration_weight(value: number)
  get state_radius(): number
  set state_radius(value: number)
  get duration_extra(): number
  set duration_extra(value: number)
  get duration_extra_factor(): number
  set duration_extra_factor(value: number)
  get geometric_temperature(): number
  set geometric_temperature(value: number)
  get pruning_slope(): number
  set pruning_slope(value: number)
  get termination_threshold(): number
  set termination_threshold(value: number)
  get deterministic_annealing(): boolean
  set deterministic_annealing(value: boolean)
  get mean_frame_likelihood(): boolean
  set mean_frame_likelihood(value: boolean)
  get workers(): number
  set workers(value: number)
  constructor()
  cloned(): TrainingOptions
}

export declare class TrainingResult {
  close(): void
  free(): void
  get is_closed(): boolean
  constructor(model: Model, iterations: IterationReports)
  model(): Model
  set_model(model: Model): void
  iterations(): IterationReports
  write_likelihood_csv(): Uint8Array
  set_iterations(iterations: IterationReports): void
  cloned(): TrainingResult
}

export declare class UntiedModel {
  close(): void
  free(): void
  get is_closed(): boolean
  constructor(model: Model, segmentation: SegmentationDocument, assignments: Assignments)
  model(): Model
  set_model(value: Model): void
  segmentation(): SegmentationDocument
  set_segmentation(value: SegmentationDocument): void
  assignments(): Assignments
  set_assignments(value: Assignments): void
  cloned(): UntiedModel
  write_summary(): Uint8Array
}

export declare class UtteranceModelSource {
  close(): void
  free(): void
  get is_closed(): boolean
  static fresh(): UtteranceModelSource
  static initialized(model: Model): UtteranceModelSource
  static trained(model: Model): UtteranceModelSource
  get kind(): number
  model(): Model | null
  cloned(): UtteranceModelSource
}

export declare class UtteranceOptions {
  close(): void
  free(): void
  get is_closed(): boolean
  get utterances(): number
  set utterances(value: number)
  get hop_seconds(): number
  set hop_seconds(value: number)
  get minimum_silence_seconds(): number
  set minimum_silence_seconds(value: number)
  get minimum_voicing_seconds(): number
  set minimum_voicing_seconds(value: number)
  get iterations(): number
  set iterations(value: number)
  constructor()
  cloned(): UtteranceOptions
}

export declare class Wave {
  close(): void
  free(): void
  get is_closed(): boolean
  constructor(sampleRate: number, bitsPerSample: number, channels: number, encoding: number, samples: Float32Array)
  static read(bytes: Uint8Array, maximumFrames: number): Wave
  get sample_rate(): number
  set sample_rate(value: number)
  get bits_per_sample(): number
  set bits_per_sample(value: number)
  get channels(): number
  set channels(value: number)
  get encoding(): number
  set encoding(value: number)
  samples(): Float32Array
  set_samples(samples: Float32Array): void
  cloned(): Wave
}

export declare function batch_extract_file(stem: string, options: BatchOptions, extractor: Extractor, uniform: () => number): BatchOutputs

export declare function batch_feature_options(value: number): FeatureOptions

export declare function feature_frame_count(bytes: bigint, dimensions: number): number

export declare function index_append_suffix(path: string, suffix: string): string

export declare function label_output_path(filename: string, suffix: string): string

export declare function rawfloat_read(bytes: Uint8Array, maximumSamples: number): Float32Array

export declare function rawfloat_write(values: Float32Array): Uint8Array

export declare function version(): string
