const path = require('node:path');
const api = require(path.join(path.resolve(process.argv[2]), 'shiro_rs.js'));
const owners = ['Label', 'Labels', 'PhoneMap', 'States', 'ModelDefinition', 'SegmentationDocument', 'PhoneMapOptions', 'Duration', 'Durations', 'Gaussian', 'Gaussians', 'Stream', 'Streams', 'Model', 'DecodedModel', 'ObservationStream', 'ObservationStreams', 'Observation', 'JumpGroup', 'Segmentation', 'IsolatedGroup', 'IsolatedGroups', 'Observations', 'Segmentations', 'Dataset', 'InitializationOptions', 'FeatureFiles', 'Datasets', 'TrainingOptions', 'FileLikelihoods', 'LikelihoodRows', 'IterationReport', 'IterationReports', 'TrainingResult', 'AlignmentOptions', 'Assignment', 'Assignments', 'UntiedModel', 'FeatureOptions', 'Features'];
const functions = ['rawfloat_read', 'rawfloat_write', 'label_output_path'];
functions.push('index_append_suffix');
functions.push('batch_feature_options');
owners.push('AudioOptions', 'Audio', 'Wave', 'DitherSequence');
owners.push('UtteranceOptions', 'UtteranceModelSource', 'SegmentedUtterances', 'SegmentedWave');
owners.push('IndexEntry', 'IndexEntries');
owners.push('BatchOptions', 'BatchOutputs', 'BatchExtraction');
for (const name of [...owners, ...functions]) if (name in api) throw new Error('Disabled WASM export: ' + name);
console.log('SHIRO WASM feature disabled:', JSON.stringify({owners: owners.length, functions: functions.length}));
