function assert(value, message) { if (!value) throw new Error(message); }
function equal(actual, expected, message) { assert(actual.length === expected.length && actual.every((value, index) => Object.is(value, expected[index])), message); }
function rejects(run, message) { let failed = false; try { run(); } catch { failed = true; } assert(failed, message); }
function floats(bytes) { const view = new DataView(bytes.buffer, bytes.byteOffset, bytes.byteLength); return Float32Array.from({length: bytes.length / 4}, (_, index) => view.getFloat32(index * 4, true)); }
function snapshot(result) { const audio = result.audio(), features = result.features(), outputs = result.outputs(); const value = {rate: audio.sample_rate, audio: Array.from(audio.samples()), frames: features.frames, columns: features.columns, features: Array.from(features.values()), raw: outputs.raw, parameters: outputs.parameters, mfcc: outputs.mfcc}; audio.free(); features.free(); outputs.free(); return value; }
export async function verifyBatch(api, load) {
    const wave = api.Wave.read(new Uint8Array(await load('c-audio-input.wav')), 1024), options = new api.BatchOptions(); assert(options.input_extension === '.wav', 'native batch default extension');
    const defaultAudio = options.audio(); assert(!defaultAudio.normalize && defaultAudio.dither_level === 0 && defaultAudio.output_sample_rate === undefined && defaultAudio.boundary === 0 && defaultAudio.kernel === 0, 'all native nested defaults'); defaultAudio.free();
    let valuesChecked = 0, maximumNormalizedError = 0;
    for (const [preset, name, columns] of [[0, 'mfcc12-da', 36], [1, 'mfcc12-dae', 39], [2, 'plpcc12-da', 36]]) {
        const settings = api.batch_feature_options(preset), expectedSettings = {kind: preset === 2 ? 2 : 0, order: 12, channels: 36, frame_length: 512, hop: 80, sample_rate_hz: 16000, minimum_bandwidth_hz: 400, warp: 1, include_dc: false, energy: preset === 1 ? 1 : 0, delta: true, acceleration: true};
        for (const [key, value] of Object.entries(expectedSettings)) assert(settings[key] === value, 'all native preset settings ' + key); settings.free();
        const result = api.BatchExtraction.extract(wave, 'dir/clip with spaces.v1', options, preset, () => {throw new Error('unexpected default dither');}), actual = snapshot(result), expected = floats(new Uint8Array(await load('c-fextr-' + name + '.bin')));
        equal(api.rawfloat_write(Float32Array.from(actual.audio)), new Uint8Array(await load('c-audio-input.plain.raw')), 'complete C batch raw bytes');
        assert(actual.frames === 3 && actual.columns === columns && actual.features.length === expected.length && actual.raw === 'dir/clip with spaces.v1.raw' && actual.parameters === 'dir/clip with spaces.v1.param' && actual.mfcc === undefined, 'complete native batch output shape and names');
        actual.features.forEach((value, index) => { const error = Math.abs(value - expected[index]) / Math.max(Math.abs(expected[index]), 1); maximumNormalizedError = Math.max(maximumNormalizedError, error); assert(error < 2e-5, 'C batch feature tolerance'); valuesChecked++; });
        const clone = result.cloned(); result.free(); assert(JSON.stringify(snapshot(clone)) === JSON.stringify(actual), 'complete result survives source release'); clone.free();
    }
    rejects(() => api.batch_feature_options(3), 'invalid preset options');
    const audioOptions = new api.AudioOptions(); Object.assign(audioOptions, {normalize: true, output_sample_rate: 8000, boundary: 1, kernel: 1}); options.set_audio(audioOptions); options.input_extension = '.source.wav'; audioOptions.free();
    const cloneOptions = options.cloned(), nested = cloneOptions.audio(); assert(nested.normalize && nested.output_sample_rate === 8000 && nested.boundary === 1 && nested.kernel === 1 && cloneOptions.input_extension === '.source.wav', 'both options fields copied'); nested.normalize = false; nested.free();
    const altered = api.BatchExtraction.extract(wave, '\u97f3.v2', cloneOptions, 0, () => {throw new Error('unexpected draw');}), value = snapshot(altered); equal(api.rawfloat_write(Float32Array.from(value.audio)), new Uint8Array(await load('c-audio-input.normalized-down.raw')), 'nondefault preparation C raw bytes'); assert(value.raw === '\u97f3.v2.raw' && value.parameters === '\u97f3.v2.param' && value.frames === 1, 'custom input suffix does not alter output stem');
    const alteredCopy = altered.cloned(); for (const field of ['audio', 'features', 'outputs']) { const child = altered[field](); alteredCopy['set_' + field](child); child.free(); } altered.free(); assert(JSON.stringify(snapshot(alteredCopy)) === JSON.stringify(value), 'all result fields copied and editable'); alteredCopy.free(); cloneOptions.free();
    const dither = new api.AudioOptions(); dither.dither_level = .125; options.set_audio(dither); dither.free(); const random = api.DitherSequence.linux_gnu(), dithered = api.BatchExtraction.extract_with_sequence(wave, 'dither', options, 1, random), ditherValue = snapshot(dithered); equal(api.rawfloat_write(Float32Array.from(ditherValue.audio)), new Uint8Array(await load('c-audio-input.dither-linux.raw')), 'complete C dithered batch audio'); dithered.free(); random.free();
    const callbackRandom = api.DitherSequence.linux_gnu(); let calls = 0; const live = api.BatchExtraction.extract(wave, 'dither', options, 1, () => {calls++; return callbackRandom.next_uniform();}); assert(calls === wave.samples().length && JSON.stringify(snapshot(live)) === JSON.stringify(ditherValue), 'live callback and sequence retain full output'); live.free(); callbackRandom.free();
    const failure = {batch: 'identity'}; let caught; calls = 0; try { api.BatchExtraction.extract(wave, 'failed', options, 0, () => {calls++; throw failure;}); } catch (value) {caught = value;} assert(caught === failure && calls === 1, 'callback exception identity and stop');
    for (const extension of ['.raw', '.param']) { options.input_extension = extension; calls = 0; rejects(() => api.BatchExtraction.extract(wave, 'alias', options, 0, () => {calls++; return .5;}), 'input/output alias'); assert(calls === 0, 'alias rejected before RNG'); } options.input_extension = '.wav';
    calls = 0; rejects(() => api.BatchExtraction.extract(wave, 'invalid', options, 3, () => {calls++; return .5;}), 'invalid preset extraction'); assert(calls === 0, 'invalid preset consumes no draws');
    rejects(() => api.BatchExtraction.extract(wave, 'invalid', options, 0, () => '0.5'), 'nonnumeric draw');
    const reset = new api.AudioOptions(); options.set_audio(reset); reset.free(); const empty = new api.Wave(8000, 32, 1, 1, new Float32Array()), emptyResult = api.BatchExtraction.extract(empty, '', options, 0, () => {throw failure;}), emptyValue = snapshot(emptyResult); assert(emptyValue.frames === 0 && emptyValue.audio.length === 0 && emptyValue.raw === '.raw', 'empty input and stem'); emptyResult.free(); empty.free();
    const bad = new api.Wave(8000, 32, 1, 1, new Float32Array([NaN])); rejects(() => api.BatchExtraction.extract(bad, 'bad', options, 0, () => .5), 'nonfinite input'); bad.free();
    const outputs = new api.BatchOutputs('raw', 'parameters', 'mfcc'), copiedOutputs = outputs.cloned(); outputs.raw = '\u97f3\u0000.raw'; outputs.parameters = ''; outputs.mfcc = undefined; assert(outputs.raw === '\u97f3\u0000.raw' && outputs.parameters === '' && outputs.mfcc === undefined, 'all output fields editable including absence'); outputs.mfcc = ''; assert(outputs.mfcc === '', 'empty optional path differs from absence');
    const rawAudio = new api.Audio(0, new Float32Array([NaN])), rawFeatures = new api.Features(9, 99, new Float32Array([-0])), arbitrary = new api.BatchExtraction(rawAudio, rawFeatures, outputs); arbitrary.set_outputs(copiedOutputs); outputs.free(); copiedOutputs.free(); rawAudio.free(); rawFeatures.free();
    const rawChild = arbitrary.audio(), featureChild = arbitrary.features(), paths = arbitrary.outputs(); assert(rawChild.sample_rate === 0 && Number.isNaN(rawChild.samples()[0]) && featureChild.frames === 9 && featureChild.columns === 99 && Object.is(featureChild.values()[0], -0) && paths.mfcc === 'mfcc', 'arbitrary composite and optional paths survive source release'); rawChild.free(); featureChild.free(); paths.free(); arbitrary.free();
    wave.free(); options.free(); return {originalCPresets: 3, valuesChecked, maximumNormalizedError, presetFields: 12, optionFields: 2, outputFields: 3, resultFields: 3};
}
