from collections.abc import Callable, Sequence
from typing import Any

__version__: str

class AlignmentOptions:
    def close(self) -> None: ...
    def free(self) -> None: ...
    @property
    def is_closed(self) -> bool: ...
    @property
    def duration_mode(self) -> int: ...
    @duration_mode.setter
    def duration_mode(self, value: int) -> None: ...
    @property
    def isolated(self) -> bool: ...
    @isolated.setter
    def isolated(self, value: bool) -> None: ...
    @property
    def hsmm_temperature(self) -> float: ...
    @hsmm_temperature.setter
    def hsmm_temperature(self, value: float) -> None: ...
    @property
    def duration_weight(self) -> float: ...
    @duration_weight.setter
    def duration_weight(self, value: float) -> None: ...
    @property
    def state_radius(self) -> float: ...
    @state_radius.setter
    def state_radius(self, value: float) -> None: ...
    @property
    def duration_extra(self) -> int: ...
    @duration_extra.setter
    def duration_extra(self, value: int) -> None: ...
    @property
    def duration_extra_factor(self) -> float: ...
    @duration_extra_factor.setter
    def duration_extra_factor(self, value: float) -> None: ...
    @property
    def geometric_temperature(self) -> float: ...
    @geometric_temperature.setter
    def geometric_temperature(self, value: float) -> None: ...
    @property
    def pruning_slope(self) -> float: ...
    @pruning_slope.setter
    def pruning_slope(self, value: float) -> None: ...
    def __init__(self) -> None: ...
    def cloned(self) -> AlignmentOptions: ...

class Assignment:
    def close(self) -> None: ...
    def free(self) -> None: ...
    @property
    def is_closed(self) -> bool: ...
    @property
    def state(self) -> int: ...
    @state.setter
    def state(self, value: int) -> None: ...
    @property
    def file(self) -> int: ...
    @file.setter
    def file(self, value: int) -> None: ...
    @property
    def segment(self) -> int: ...
    @segment.setter
    def segment(self, value: int) -> None: ...
    def __init__(self, state: int, file: int, segment: int) -> None: ...
    def cloned(self) -> Assignment: ...

class Assignments:
    def close(self) -> None: ...
    def free(self) -> None: ...
    @property
    def is_closed(self) -> bool: ...
    def __init__(self) -> None: ...
    @property
    def length(self) -> int: ...
    def get(self, index: int) -> Assignment | None: ...
    def push(self, value: Assignment) -> None: ...
    def replace(self, index: int, value: Assignment) -> None: ...
    def clear(self) -> None: ...
    def cloned(self) -> Assignments: ...

class Audio:
    def close(self) -> None: ...
    def free(self) -> None: ...
    @property
    def is_closed(self) -> bool: ...
    def __init__(self, sample_rate: int, samples: Sequence[float]) -> None: ...
    @property
    def sample_rate(self) -> int: ...
    @sample_rate.setter
    def sample_rate(self, value: int) -> None: ...
    def samples(self) -> list[float]: ...
    def set_samples(self, samples: Sequence[float]) -> None: ...
    def cloned(self) -> Audio: ...
    @staticmethod
    def prepare_with_sequence(wave: Wave, options: AudioOptions, sequence: DitherSequence) -> Audio: ...
    @staticmethod
    def prepare(wave: Wave, options: AudioOptions, uniform: Callable[[], float]) -> Audio: ...

class AudioOptions:
    def close(self) -> None: ...
    def free(self) -> None: ...
    @property
    def is_closed(self) -> bool: ...
    @property
    def normalize(self) -> bool: ...
    @normalize.setter
    def normalize(self, value: bool) -> None: ...
    @property
    def dither_level(self) -> float: ...
    @dither_level.setter
    def dither_level(self, value: float) -> None: ...
    @property
    def output_sample_rate(self) -> int | None: ...
    @output_sample_rate.setter
    def output_sample_rate(self, value: int | None) -> None: ...
    @property
    def boundary(self) -> int: ...
    @boundary.setter
    def boundary(self, value: int) -> None: ...
    @property
    def kernel(self) -> int: ...
    @kernel.setter
    def kernel(self, value: int) -> None: ...
    def __init__(self) -> None: ...
    def cloned(self) -> AudioOptions: ...

class BatchExtraction:
    def close(self) -> None: ...
    def free(self) -> None: ...
    @property
    def is_closed(self) -> bool: ...
    def __init__(self, audio: Audio, features: Features, outputs: BatchOutputs) -> None: ...
    def audio(self) -> Audio: ...
    def set_audio(self, value: Audio) -> None: ...
    def features(self) -> Features: ...
    def set_features(self, value: Features) -> None: ...
    def outputs(self) -> BatchOutputs: ...
    def set_outputs(self, value: BatchOutputs) -> None: ...
    def cloned(self) -> BatchExtraction: ...
    @staticmethod
    def extract_with_sequence(wave: Wave, stem: str, options: BatchOptions, value: int, sequence: DitherSequence) -> BatchExtraction: ...
    @staticmethod
    def extract(wave: Wave, stem: str, options: BatchOptions, value: int, uniform: Callable[[], float]) -> BatchExtraction: ...

class BatchOptions:
    def close(self) -> None: ...
    def free(self) -> None: ...
    @property
    def is_closed(self) -> bool: ...
    def __init__(self) -> None: ...
    def audio(self) -> AudioOptions: ...
    def set_audio(self, value: AudioOptions) -> None: ...
    @property
    def input_extension(self) -> str: ...
    @input_extension.setter
    def input_extension(self, value: str) -> None: ...
    def cloned(self) -> BatchOptions: ...

class BatchOutputs:
    def close(self) -> None: ...
    def free(self) -> None: ...
    @property
    def is_closed(self) -> bool: ...
    @property
    def raw(self) -> str: ...
    @raw.setter
    def raw(self, value: str) -> None: ...
    @property
    def parameters(self) -> str: ...
    @parameters.setter
    def parameters(self, value: str) -> None: ...
    @property
    def mfcc(self) -> str | None: ...
    @mfcc.setter
    def mfcc(self, value: str | None) -> None: ...
    def __init__(self, raw: str, parameters: str, mfcc: str | None) -> None: ...
    def cloned(self) -> BatchOutputs: ...

class Dataset:
    def close(self) -> None: ...
    def free(self) -> None: ...
    @property
    def is_closed(self) -> bool: ...
    def __init__(self) -> None: ...
    def observations(self) -> Observations: ...
    def segmentations(self) -> Segmentations: ...
    def set_observations(self, values: Observations) -> None: ...
    def set_segmentations(self, values: Segmentations) -> None: ...
    def replace(self, observations: Observations, segmentations: Segmentations) -> None: ...
    def cloned(self) -> Dataset: ...
    @staticmethod
    def load_files(document: SegmentationDocument, model: Model, maximum_frames: int) -> Dataset: ...
    @staticmethod
    def load(document: SegmentationDocument, model: Model, files: FeatureFiles, maximum_frames: int) -> Dataset: ...

class Datasets:
    @staticmethod
    def load_training_paths(document: SegmentationDocument, model: Model, maximum_frames: int, isolated: bool) -> Datasets: ...
    def close(self) -> None: ...
    def free(self) -> None: ...
    @property
    def is_closed(self) -> bool: ...
    def __init__(self) -> None: ...
    @property
    def length(self) -> int: ...
    def get(self, index: int) -> Dataset | None: ...
    def push(self, value: Dataset) -> None: ...
    def replace(self, index: int, value: Dataset) -> None: ...
    def clear(self) -> None: ...
    def cloned(self) -> Datasets: ...
    @staticmethod
    def load_training_files(document: SegmentationDocument, model: Model, files: FeatureFiles, maximum_frames: int, isolated: bool) -> Datasets: ...

class DecodedModel:
    def close(self) -> None: ...
    def free(self) -> None: ...
    @property
    def is_closed(self) -> bool: ...
    @property
    def position(self) -> int: ...
    def parameters(self) -> Model: ...
    def into_parameters(self) -> Model: ...

class DitherSequence:
    def close(self) -> None: ...
    def free(self) -> None: ...
    @property
    def is_closed(self) -> bool: ...
    @staticmethod
    def windows() -> DitherSequence: ...
    @staticmethod
    def linux_gnu() -> DitherSequence: ...
    def next_uniform(self) -> float: ...

class Duration:
    def close(self) -> None: ...
    def free(self) -> None: ...
    @property
    def is_closed(self) -> bool: ...
    def __init__(self) -> None: ...
    def values(self) -> list[float]: ...
    def constraints(self) -> list[int]: ...
    def set_values(self, values: Sequence[float]) -> None: ...
    def set_constraints(self, values: Sequence[int]) -> None: ...
    def cloned(self) -> Duration: ...

class Durations:
    def close(self) -> None: ...
    def free(self) -> None: ...
    @property
    def is_closed(self) -> bool: ...
    def __init__(self) -> None: ...
    @property
    def length(self) -> int: ...
    def get(self, index: int) -> Duration | None: ...
    def push(self, value: Duration) -> None: ...
    def replace(self, index: int, value: Duration) -> None: ...
    def clear(self) -> None: ...
    def cloned(self) -> Durations: ...

class Extractor:
    def close(self) -> None: ...
    def free(self) -> None: ...
    @property
    def is_closed(self) -> bool: ...
    @staticmethod
    def native(preset: int) -> Extractor: ...
    @staticmethod
    def sptk(programs: SptkPrograms) -> Extractor: ...
    @staticmethod
    def lua(interpreter: str, script: str, executable_directory: str) -> Extractor: ...
    def cloned(self) -> Extractor: ...

class FeatureFiles:
    def close(self) -> None: ...
    def free(self) -> None: ...
    @property
    def is_closed(self) -> bool: ...
    def __init__(self) -> None: ...
    @property
    def length(self) -> int: ...
    def names(self) -> list[str]: ...
    def get(self, filename: str) -> bytes | None: ...
    def set(self, filename: str, bytes: Sequence[int]) -> None: ...
    def remove(self, filename: str) -> bool: ...
    def clear(self) -> None: ...
    def cloned(self) -> FeatureFiles: ...

class FeatureOptions:
    def close(self) -> None: ...
    def free(self) -> None: ...
    @property
    def is_closed(self) -> bool: ...
    @property
    def kind(self) -> int: ...
    @kind.setter
    def kind(self, value: int) -> None: ...
    @property
    def order(self) -> int: ...
    @order.setter
    def order(self, value: int) -> None: ...
    @property
    def channels(self) -> int: ...
    @channels.setter
    def channels(self, value: int) -> None: ...
    @property
    def frame_length(self) -> int: ...
    @frame_length.setter
    def frame_length(self, value: int) -> None: ...
    @property
    def hop(self) -> float: ...
    @hop.setter
    def hop(self, value: float) -> None: ...
    @property
    def sample_rate_hz(self) -> float: ...
    @sample_rate_hz.setter
    def sample_rate_hz(self, value: float) -> None: ...
    @property
    def minimum_bandwidth_hz(self) -> float: ...
    @minimum_bandwidth_hz.setter
    def minimum_bandwidth_hz(self, value: float) -> None: ...
    @property
    def warp(self) -> float: ...
    @warp.setter
    def warp(self, value: float) -> None: ...
    @property
    def include_dc(self) -> bool: ...
    @include_dc.setter
    def include_dc(self, value: bool) -> None: ...
    @property
    def energy(self) -> int: ...
    @energy.setter
    def energy(self, value: int) -> None: ...
    @property
    def delta(self) -> bool: ...
    @delta.setter
    def delta(self, value: bool) -> None: ...
    @property
    def acceleration(self) -> bool: ...
    @acceleration.setter
    def acceleration(self, value: bool) -> None: ...
    def __init__(self) -> None: ...
    def cloned(self) -> FeatureOptions: ...

class Features:
    def close(self) -> None: ...
    def free(self) -> None: ...
    @property
    def is_closed(self) -> bool: ...
    def __init__(self, frames: int, columns: int, values: Sequence[float]) -> None: ...
    @staticmethod
    def extract(signal: Sequence[float], options: FeatureOptions) -> Features: ...
    @property
    def frames(self) -> int: ...
    @frames.setter
    def frames(self, value: int) -> None: ...
    @property
    def columns(self) -> int: ...
    @columns.setter
    def columns(self, value: int) -> None: ...
    def values(self) -> list[float]: ...
    def set_values(self, values: Sequence[float]) -> None: ...
    def cloned(self) -> Features: ...

class FileLikelihoods:
    def close(self) -> None: ...
    def free(self) -> None: ...
    @property
    def is_closed(self) -> bool: ...
    def __init__(self, values: Sequence[float]) -> None: ...
    def values(self) -> list[float]: ...
    def replace(self, values: Sequence[float]) -> None: ...
    def cloned(self) -> FileLikelihoods: ...

class Gaussian:
    def close(self) -> None: ...
    def free(self) -> None: ...
    @property
    def is_closed(self) -> bool: ...
    def __init__(self, components: int, dimensions: int) -> None: ...
    @property
    def dimensions(self) -> int: ...
    @property
    def components(self) -> int: ...
    def weights(self) -> list[float]: ...
    def means(self) -> list[float]: ...
    def variances(self) -> list[float]: ...
    def variance_floors(self) -> list[float]: ...
    def replace(self, dimensions: int, weights: Sequence[float], means: Sequence[float], variances: Sequence[float], variance_floors: Sequence[float]) -> None: ...
    def cloned(self) -> Gaussian: ...

class Gaussians:
    def close(self) -> None: ...
    def free(self) -> None: ...
    @property
    def is_closed(self) -> bool: ...
    def __init__(self) -> None: ...
    @property
    def length(self) -> int: ...
    def get(self, index: int) -> Gaussian | None: ...
    def push(self, value: Gaussian) -> None: ...
    def replace(self, index: int, value: Gaussian) -> None: ...
    def clear(self) -> None: ...
    def cloned(self) -> Gaussians: ...

class IndexEntries:
    def close(self) -> None: ...
    def free(self) -> None: ...
    @property
    def is_closed(self) -> bool: ...
    def __init__(self) -> None: ...
    @property
    def length(self) -> int: ...
    def get(self, index: int) -> IndexEntry | None: ...
    def push(self, value: IndexEntry) -> None: ...
    def replace(self, index: int, value: IndexEntry) -> None: ...
    def clear(self) -> None: ...
    def cloned(self) -> IndexEntries: ...
    @staticmethod
    def read(bytes: Sequence[int], directory: str, left_json: str, right_json: str) -> IndexEntries: ...

class IndexEntry:
    def close(self) -> None: ...
    def free(self) -> None: ...
    @property
    def is_closed(self) -> bool: ...
    def __init__(self, stem: str, phonemes_json: str) -> None: ...
    @property
    def stem(self) -> str: ...
    @stem.setter
    def stem(self, stem: str) -> None: ...
    def phonemes_json(self) -> str: ...
    def set_phonemes_json(self, json: str) -> None: ...
    def cloned(self) -> IndexEntry: ...

class InitializationOptions:
    def close(self) -> None: ...
    def free(self) -> None: ...
    @property
    def is_closed(self) -> bool: ...
    @property
    def flat_start(self) -> bool: ...
    @flat_start.setter
    def flat_start(self, value: bool) -> None: ...
    @property
    def globally_tied(self) -> bool: ...
    @globally_tied.setter
    def globally_tied(self, value: bool) -> None: ...
    @property
    def variance_floor_ratio(self) -> float: ...
    @variance_floor_ratio.setter
    def variance_floor_ratio(self, value: float) -> None: ...
    def __init__(self) -> None: ...
    def cloned(self) -> InitializationOptions: ...

class IsolatedGroup:
    def close(self) -> None: ...
    def free(self) -> None: ...
    @property
    def is_closed(self) -> bool: ...
    def __init__(self, first_state: int, first_frame: int, observation: Observation, states: States) -> None: ...
    @property
    def first_state(self) -> int: ...
    @first_state.setter
    def first_state(self, value: int) -> None: ...
    @property
    def first_frame(self) -> int: ...
    @first_frame.setter
    def first_frame(self, value: int) -> None: ...
    def observation(self) -> Observation: ...
    def set_observation(self, value: Observation) -> None: ...
    def states(self) -> States: ...
    def set_states(self, value: States) -> None: ...
    def cloned(self) -> IsolatedGroup: ...

class IsolatedGroups:
    def close(self) -> None: ...
    def free(self) -> None: ...
    @property
    def is_closed(self) -> bool: ...
    def __init__(self) -> None: ...
    @property
    def length(self) -> int: ...
    def get(self, index: int) -> IsolatedGroup | None: ...
    def push(self, value: IsolatedGroup) -> None: ...
    def replace(self, index: int, value: IsolatedGroup) -> None: ...
    def clear(self) -> None: ...
    def cloned(self) -> IsolatedGroups: ...
    @staticmethod
    def split(model: Model, observation: Observation, states: States) -> IsolatedGroups: ...

class IterationReport:
    def close(self) -> None: ...
    def free(self) -> None: ...
    @property
    def is_closed(self) -> bool: ...
    def __init__(self, iteration: int, temperature: float, mean_log_likelihood: float, rows: LikelihoodRows) -> None: ...
    @property
    def iteration(self) -> int: ...
    @iteration.setter
    def iteration(self, value: int) -> None: ...
    @property
    def temperature(self) -> float: ...
    @temperature.setter
    def temperature(self, value: float) -> None: ...
    @property
    def mean_log_likelihood(self) -> float: ...
    @mean_log_likelihood.setter
    def mean_log_likelihood(self, value: float) -> None: ...
    def file_likelihoods(self) -> LikelihoodRows: ...
    def set_file_likelihoods(self, rows: LikelihoodRows) -> None: ...
    def cloned(self) -> IterationReport: ...

class IterationReports:
    def close(self) -> None: ...
    def free(self) -> None: ...
    @property
    def is_closed(self) -> bool: ...
    def __init__(self) -> None: ...
    @property
    def length(self) -> int: ...
    def get(self, index: int) -> IterationReport | None: ...
    def push(self, value: IterationReport) -> None: ...
    def replace(self, index: int, value: IterationReport) -> None: ...
    def clear(self) -> None: ...
    def cloned(self) -> IterationReports: ...

class JumpGroup:
    def close(self) -> None: ...
    def free(self) -> None: ...
    @property
    def is_closed(self) -> bool: ...
    def __init__(self, deltas: Sequence[int], probabilities: Sequence[float]) -> None: ...
    @property
    def length(self) -> int: ...
    def deltas(self) -> list[int]: ...
    def probabilities(self) -> list[float]: ...
    def cloned(self) -> JumpGroup: ...

class Label:
    def close(self) -> None: ...
    def free(self) -> None: ...
    @property
    def is_closed(self) -> bool: ...
    @property
    def start(self) -> float: ...
    @start.setter
    def start(self, value: float) -> None: ...
    @property
    def end(self) -> float: ...
    @end.setter
    def end(self, value: float) -> None: ...
    def __init__(self, start: float, end: float, name: str) -> None: ...
    @property
    def name(self) -> str: ...
    @name.setter
    def name(self, name: str) -> None: ...
    def cloned(self) -> Label: ...

class Labels:
    def close(self) -> None: ...
    def free(self) -> None: ...
    @property
    def is_closed(self) -> bool: ...
    def __init__(self) -> None: ...
    @staticmethod
    def parse(text: str) -> Labels: ...
    @property
    def length(self) -> int: ...
    def get(self, index: int) -> Label | None: ...
    def push(self, label: Label) -> None: ...
    def replace(self, index: int, label: Label) -> None: ...
    def clear(self) -> None: ...
    def cloned(self) -> Labels: ...
    def write(self) -> bytes: ...
    def to_states(self, map: PhoneMap, hop: float) -> States: ...
    @staticmethod
    def from_states(states: States, hop: float, include_states: bool) -> Labels: ...

class LikelihoodRows:
    def close(self) -> None: ...
    def free(self) -> None: ...
    @property
    def is_closed(self) -> bool: ...
    def __init__(self) -> None: ...
    @property
    def length(self) -> int: ...
    def get(self, index: int) -> FileLikelihoods | None: ...
    def push(self, value: FileLikelihoods) -> None: ...
    def replace(self, index: int, value: FileLikelihoods) -> None: ...
    def clear(self) -> None: ...
    def cloned(self) -> LikelihoodRows: ...

class Model:
    def align_states(self, observation: Observation, states: States, options: AlignmentOptions) -> States: ...
    def align_document(self, document: SegmentationDocument, files: FeatureFiles, maximum_frames: int, options: AlignmentOptions) -> SegmentationDocument: ...
    @staticmethod
    def read_file(path: str) -> Model: ...
    def write_file(self, path: str, encoding: int) -> None: ...
    def align_document_files(self, document: SegmentationDocument, options: AlignmentOptions) -> SegmentationDocument: ...
    def initialize(self, dataset: Dataset, options: InitializationOptions) -> Model: ...
    def close(self) -> None: ...
    def free(self) -> None: ...
    @property
    def is_closed(self) -> bool: ...
    def __init__(self) -> None: ...
    @property
    def streams(self) -> int: ...
    @property
    def durations(self) -> int: ...
    def stream(self, index: int) -> Stream | None: ...
    def duration(self, index: int) -> Duration | None: ...
    def set_stream(self, index: int, value: Stream) -> None: ...
    def set_duration(self, index: int, value: Duration) -> None: ...
    def replace(self, streams: Streams, durations: Durations) -> None: ...
    def cloned(self) -> Model: ...
    def validate(self) -> None: ...
    def dimensions(self) -> list[int]: ...
    @staticmethod
    def read(bytes: Sequence[int]) -> Model: ...
    @staticmethod
    def read_with_limits(bytes: Sequence[int], max_array_entries: int) -> Model: ...
    @staticmethod
    def read_prefix(bytes: Sequence[int]) -> DecodedModel: ...
    @staticmethod
    def read_prefix_with_limits(bytes: Sequence[int], max_array_entries: int) -> DecodedModel: ...
    def write(self) -> bytes: ...
    def write_with_encoding(self, code: int) -> bytes: ...
    def train(self, files: Datasets, options: TrainingOptions) -> TrainingResult: ...
    def train_with_progress(self, files: Datasets, options: TrainingOptions, progress: Callable[[IterationReport], None]) -> TrainingResult: ...
    def untie(self, document: SegmentationDocument) -> UntiedModel: ...

class ModelDefinition:
    def close(self) -> None: ...
    def free(self) -> None: ...
    @property
    def is_closed(self) -> bool: ...
    def __init__(self, json: str) -> None: ...
    def json(self) -> str: ...
    def replace(self, json: str) -> None: ...
    def cloned(self) -> ModelDefinition: ...
    def build(self) -> Model: ...

class Observation:
    def close(self) -> None: ...
    def free(self) -> None: ...
    @property
    def is_closed(self) -> bool: ...
    def __init__(self, frames: int, dimensions: Sequence[int]) -> None: ...
    @staticmethod
    def read_rawfloat(bytes: Sequence[int], dimensions: Sequence[int], maximum_frames: int) -> Observation: ...
    @staticmethod
    def from_model_rawfloat(bytes: Sequence[int], model: Model, maximum_frames: int) -> Observation: ...
    @property
    def frames(self) -> int: ...
    @property
    def streams(self) -> int: ...
    def stream(self, index: int) -> ObservationStream | None: ...
    def set_stream(self, index: int, value: ObservationStream) -> None: ...
    def replace(self, frames: int, streams: ObservationStreams) -> None: ...
    def frame(self, stream: int, time: int) -> list[float] | None: ...
    def validate(self) -> None: ...
    def cloned(self) -> Observation: ...
    def write(self) -> bytes: ...

class ObservationStream:
    def close(self) -> None: ...
    def free(self) -> None: ...
    @property
    def is_closed(self) -> bool: ...
    def __init__(self, dimensions: int, values: Sequence[float]) -> None: ...
    @property
    def dimensions(self) -> int: ...
    def values(self) -> list[float]: ...
    def replace(self, dimensions: int, values: Sequence[float]) -> None: ...
    def cloned(self) -> ObservationStream: ...

class ObservationStreams:
    def close(self) -> None: ...
    def free(self) -> None: ...
    @property
    def is_closed(self) -> bool: ...
    def __init__(self) -> None: ...
    @property
    def length(self) -> int: ...
    def get(self, index: int) -> ObservationStream | None: ...
    def push(self, value: ObservationStream) -> None: ...
    def replace(self, index: int, value: ObservationStream) -> None: ...
    def clear(self) -> None: ...
    def cloned(self) -> ObservationStreams: ...

class Observations:
    def close(self) -> None: ...
    def free(self) -> None: ...
    @property
    def is_closed(self) -> bool: ...
    def __init__(self) -> None: ...
    @property
    def length(self) -> int: ...
    def get(self, index: int) -> Observation | None: ...
    def push(self, value: Observation) -> None: ...
    def replace(self, index: int, value: Observation) -> None: ...
    def clear(self) -> None: ...
    def cloned(self) -> Observations: ...

class PhoneMap:
    def close(self) -> None: ...
    def free(self) -> None: ...
    @property
    def is_closed(self) -> bool: ...
    def __init__(self, json: str) -> None: ...
    def json(self) -> str: ...
    def replace(self, json: str) -> None: ...
    def cloned(self) -> PhoneMap: ...
    @staticmethod
    def create(text: str, options: PhoneMapOptions) -> PhoneMap: ...
    def to_definition(self, dimensions: int, hop: float) -> ModelDefinition: ...
    def initial(self, phones: Sequence[str], frames: int) -> States: ...

class PhoneMapOptions:
    def close(self) -> None: ...
    def free(self) -> None: ...
    @property
    def is_closed(self) -> bool: ...
    @property
    def states_per_phone(self) -> int: ...
    @states_per_phone.setter
    def states_per_phone(self, value: int) -> None: ...
    @property
    def streams(self) -> int: ...
    @streams.setter
    def streams(self, value: int) -> None: ...
    @property
    def topology(self) -> str | None: ...
    @topology.setter
    def topology(self, value: str | None) -> None: ...
    @property
    def weak_skips(self) -> bool: ...
    @weak_skips.setter
    def weak_skips(self, value: bool) -> None: ...
    def __init__(self) -> None: ...
    def cloned(self) -> PhoneMapOptions: ...

class Segmentation:
    def close(self) -> None: ...
    def free(self) -> None: ...
    @property
    def is_closed(self) -> bool: ...
    def __init__(self, streams: int, segments: int) -> None: ...
    @staticmethod
    def from_states(states: States, model: Model) -> Segmentation: ...
    @property
    def streams(self) -> int: ...
    @property
    def segments(self) -> int: ...
    def boundaries(self) -> list[int]: ...
    def duration_states(self) -> list[int]: ...
    def output_states(self, stream: int) -> list[int]: ...
    def set_boundaries(self, values: Sequence[int]) -> None: ...
    def set_duration_states(self, values: Sequence[int]) -> None: ...
    def set_output_states(self, stream: int, values: Sequence[int]) -> None: ...
    def outgoing(self, state: int) -> JumpGroup | None: ...
    def set_outgoing(self, state: int, jumps: JumpGroup) -> None: ...
    def replace(self, value: Segmentation) -> None: ...
    def validate(self) -> None: ...
    def cloned(self) -> Segmentation: ...
    def write(self) -> bytes: ...

class SegmentationDocument:
    def close(self) -> None: ...
    def free(self) -> None: ...
    @property
    def is_closed(self) -> bool: ...
    def __init__(self, json: str) -> None: ...
    def json(self) -> str: ...
    def replace(self, json: str) -> None: ...
    def cloned(self) -> SegmentationDocument: ...

class Segmentations:
    def close(self) -> None: ...
    def free(self) -> None: ...
    @property
    def is_closed(self) -> bool: ...
    def __init__(self) -> None: ...
    @property
    def length(self) -> int: ...
    def get(self, index: int) -> Segmentation | None: ...
    def push(self, value: Segmentation) -> None: ...
    def replace(self, index: int, value: Segmentation) -> None: ...
    def clear(self) -> None: ...
    def cloned(self) -> Segmentations: ...

class SegmentedUtterances:
    def close(self) -> None: ...
    def free(self) -> None: ...
    @property
    def is_closed(self) -> bool: ...
    def __init__(self, model: Model, phonemap: PhoneMap, definition: ModelDefinition, initial_segmentation: SegmentationDocument, alignment: SegmentationDocument) -> None: ...
    @staticmethod
    def split_features(features: Features, filename: str, options: UtteranceOptions, source: UtteranceModelSource) -> SegmentedUtterances: ...
    def cloned(self) -> SegmentedUtterances: ...
    def phones_json(self) -> str: ...
    def set_phones_json(self, json: str) -> None: ...
    def uninitialized_model(self) -> Model | None: ...
    def set_uninitialized_model(self, value: Model) -> None: ...
    def clear_uninitialized_model(self) -> None: ...
    def initialized_model(self) -> Model | None: ...
    def set_initialized_model(self, value: Model) -> None: ...
    def clear_initialized_model(self) -> None: ...
    def phonemap(self) -> PhoneMap: ...
    def set_phonemap(self, value: PhoneMap) -> None: ...
    def definition(self) -> ModelDefinition: ...
    def set_definition(self, value: ModelDefinition) -> None: ...
    def initial_segmentation(self) -> SegmentationDocument: ...
    def set_initial_segmentation(self, value: SegmentationDocument) -> None: ...
    def model(self) -> Model: ...
    def set_model(self, value: Model) -> None: ...
    def iterations(self) -> IterationReports: ...
    def set_iterations(self, value: IterationReports) -> None: ...
    def alignment(self) -> SegmentationDocument: ...
    def set_alignment(self, value: SegmentationDocument) -> None: ...
    def labels(self) -> Labels: ...
    def set_labels(self, value: Labels) -> None: ...

class SegmentedWave:
    def close(self) -> None: ...
    def free(self) -> None: ...
    @property
    def is_closed(self) -> bool: ...
    def __init__(self, audio: Audio, features: Features, utterances: SegmentedUtterances) -> None: ...
    @staticmethod
    def split_with_sequence(wave: Wave, filename: str, dimensions: int, kind: int, options: UtteranceOptions, source: UtteranceModelSource, sequence: DitherSequence) -> SegmentedWave: ...
    @staticmethod
    def split(wave: Wave, filename: str, dimensions: int, kind: int, options: UtteranceOptions, source: UtteranceModelSource, uniform: Callable[[], float]) -> SegmentedWave: ...
    def cloned(self) -> SegmentedWave: ...
    def audio(self) -> Audio: ...
    def set_audio(self, value: Audio) -> None: ...
    def features(self) -> Features: ...
    def set_features(self, value: Features) -> None: ...
    def utterances(self) -> SegmentedUtterances: ...
    def set_utterances(self, value: SegmentedUtterances) -> None: ...

class SptkPrograms:
    def close(self) -> None: ...
    def free(self) -> None: ...
    @property
    def is_closed(self) -> bool: ...
    @property
    def frame(self) -> str: ...
    @frame.setter
    def frame(self, value: str) -> None: ...
    @property
    def mfcc(self) -> str: ...
    @mfcc.setter
    def mfcc(self, value: str) -> None: ...
    @property
    def delta(self) -> str: ...
    @delta.setter
    def delta(self, value: str) -> None: ...
    def __init__(self) -> None: ...

class States:
    def close(self) -> None: ...
    def free(self) -> None: ...
    @property
    def is_closed(self) -> bool: ...
    def __init__(self, json: str) -> None: ...
    def json(self) -> str: ...
    def replace(self, json: str) -> None: ...
    def cloned(self) -> States: ...

class Stream:
    def close(self) -> None: ...
    def free(self) -> None: ...
    @property
    def is_closed(self) -> bool: ...
    def __init__(self, emissions: int, components: int, dimensions: int) -> None: ...
    @property
    def emissions(self) -> int: ...
    def weight(self) -> list[float]: ...
    def set_weight(self, values: Sequence[float]) -> None: ...
    def emission(self, index: int) -> Gaussian | None: ...
    def set_emission(self, index: int, value: Gaussian) -> None: ...
    def replace(self, weight: Sequence[float], emissions: Gaussians) -> None: ...
    def cloned(self) -> Stream: ...

class Streams:
    def close(self) -> None: ...
    def free(self) -> None: ...
    @property
    def is_closed(self) -> bool: ...
    def __init__(self) -> None: ...
    @property
    def length(self) -> int: ...
    def get(self, index: int) -> Stream | None: ...
    def push(self, value: Stream) -> None: ...
    def replace(self, index: int, value: Stream) -> None: ...
    def clear(self) -> None: ...
    def cloned(self) -> Streams: ...

class TrainingOptions:
    def close(self) -> None: ...
    def free(self) -> None: ...
    @property
    def is_closed(self) -> bool: ...
    @property
    def iterations(self) -> int: ...
    @iterations.setter
    def iterations(self, value: int) -> None: ...
    @property
    def duration_mode(self) -> int: ...
    @duration_mode.setter
    def duration_mode(self, value: int) -> None: ...
    @property
    def hsmm_temperature(self) -> float: ...
    @hsmm_temperature.setter
    def hsmm_temperature(self, value: float) -> None: ...
    @property
    def duration_weight(self) -> float: ...
    @duration_weight.setter
    def duration_weight(self, value: float) -> None: ...
    @property
    def state_radius(self) -> float: ...
    @state_radius.setter
    def state_radius(self, value: float) -> None: ...
    @property
    def duration_extra(self) -> int: ...
    @duration_extra.setter
    def duration_extra(self, value: int) -> None: ...
    @property
    def duration_extra_factor(self) -> float: ...
    @duration_extra_factor.setter
    def duration_extra_factor(self, value: float) -> None: ...
    @property
    def geometric_temperature(self) -> float: ...
    @geometric_temperature.setter
    def geometric_temperature(self, value: float) -> None: ...
    @property
    def pruning_slope(self) -> float: ...
    @pruning_slope.setter
    def pruning_slope(self, value: float) -> None: ...
    @property
    def termination_threshold(self) -> float: ...
    @termination_threshold.setter
    def termination_threshold(self, value: float) -> None: ...
    @property
    def deterministic_annealing(self) -> bool: ...
    @deterministic_annealing.setter
    def deterministic_annealing(self, value: bool) -> None: ...
    @property
    def mean_frame_likelihood(self) -> bool: ...
    @mean_frame_likelihood.setter
    def mean_frame_likelihood(self, value: bool) -> None: ...
    @property
    def workers(self) -> int: ...
    @workers.setter
    def workers(self, value: int) -> None: ...
    def __init__(self) -> None: ...
    def cloned(self) -> TrainingOptions: ...

class TrainingResult:
    def close(self) -> None: ...
    def free(self) -> None: ...
    @property
    def is_closed(self) -> bool: ...
    def __init__(self, model: Model, iterations: IterationReports) -> None: ...
    def model(self) -> Model: ...
    def set_model(self, model: Model) -> None: ...
    def iterations(self) -> IterationReports: ...
    def write_likelihood_csv(self) -> bytes: ...
    def set_iterations(self, iterations: IterationReports) -> None: ...
    def cloned(self) -> TrainingResult: ...

class UntiedModel:
    def close(self) -> None: ...
    def free(self) -> None: ...
    @property
    def is_closed(self) -> bool: ...
    def __init__(self, model: Model, segmentation: SegmentationDocument, assignments: Assignments) -> None: ...
    def model(self) -> Model: ...
    def set_model(self, value: Model) -> None: ...
    def segmentation(self) -> SegmentationDocument: ...
    def set_segmentation(self, value: SegmentationDocument) -> None: ...
    def assignments(self) -> Assignments: ...
    def set_assignments(self, value: Assignments) -> None: ...
    def cloned(self) -> UntiedModel: ...
    def write_summary(self) -> bytes: ...

class UtteranceModelSource:
    def close(self) -> None: ...
    def free(self) -> None: ...
    @property
    def is_closed(self) -> bool: ...
    @staticmethod
    def fresh() -> UtteranceModelSource: ...
    @staticmethod
    def initialized(model: Model) -> UtteranceModelSource: ...
    @staticmethod
    def trained(model: Model) -> UtteranceModelSource: ...
    @property
    def kind(self) -> int: ...
    def model(self) -> Model | None: ...
    def cloned(self) -> UtteranceModelSource: ...

class UtteranceOptions:
    def close(self) -> None: ...
    def free(self) -> None: ...
    @property
    def is_closed(self) -> bool: ...
    @property
    def utterances(self) -> int: ...
    @utterances.setter
    def utterances(self, value: int) -> None: ...
    @property
    def hop_seconds(self) -> float: ...
    @hop_seconds.setter
    def hop_seconds(self, value: float) -> None: ...
    @property
    def minimum_silence_seconds(self) -> float: ...
    @minimum_silence_seconds.setter
    def minimum_silence_seconds(self, value: float) -> None: ...
    @property
    def minimum_voicing_seconds(self) -> float: ...
    @minimum_voicing_seconds.setter
    def minimum_voicing_seconds(self, value: float) -> None: ...
    @property
    def iterations(self) -> int: ...
    @iterations.setter
    def iterations(self, value: int) -> None: ...
    def __init__(self) -> None: ...
    def cloned(self) -> UtteranceOptions: ...

class Wave:
    def close(self) -> None: ...
    def free(self) -> None: ...
    @property
    def is_closed(self) -> bool: ...
    def __init__(self, sample_rate: int, bits_per_sample: int, channels: int, encoding: int, samples: Sequence[float]) -> None: ...
    @staticmethod
    def read(bytes: Sequence[int], maximum_frames: int) -> Wave: ...
    @property
    def sample_rate(self) -> int: ...
    @sample_rate.setter
    def sample_rate(self, value: int) -> None: ...
    @property
    def bits_per_sample(self) -> int: ...
    @bits_per_sample.setter
    def bits_per_sample(self, value: int) -> None: ...
    @property
    def channels(self) -> int: ...
    @channels.setter
    def channels(self, value: int) -> None: ...
    @property
    def encoding(self) -> int: ...
    @encoding.setter
    def encoding(self, value: int) -> None: ...
    def samples(self) -> list[float]: ...
    def set_samples(self, samples: Sequence[float]) -> None: ...
    def cloned(self) -> Wave: ...

def batch_feature_options(value: int) -> FeatureOptions: ...

def batch_extract_file(stem: str, options: BatchOptions, extractor: Extractor, uniform: Callable[[], float]) -> BatchOutputs: ...

def feature_frame_count(bytes: int, dimensions: int) -> int: ...

def index_append_suffix(path: str, suffix: str) -> str: ...

def label_output_path(filename: str, suffix: str) -> str: ...

def rawfloat_read(bytes: Sequence[int], maximum_samples: int) -> list[float]: ...

def rawfloat_write(values: Sequence[float]) -> bytes: ...
