[package]
name = "shiro-rs"
version.workspace = true
edition = "2024"
license = "GPL-3.0-or-later"
repository = "https://github.com/Lqm1/shiro-rs"
rust-version = "1.94"


description = "Speech alignment, feature extraction and HMM/HSMM training compatible with SHIRO"
readme = "README.md"
include = ["src/**", "examples/**", "Cargo.toml", "README.md", "LICENSE"]

[dependencies]
ciglet-rs = { version = "0.1.0", git = "https://github.com/Lqm1/ciglet-rs.git", rev = "34208b5fb1757355c638a1c588ec8a7fa49fddc3" }
clap = { version = "4.6.7", features = ["derive", "error-context", "help", "std", "suggestions", "usage"], default-features = false }
liblrhsmm-rs = { version = "0.1.0", git = "https://github.com/Lqm1/liblrhsmm-rs.git", rev = "d1b32853ccc2381d04af1a1cbd0587a455e992f3" }
rand = { version = "0.10.3", default-features = false, features = ["std_rng"] }
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"
