[package]
name = "shiro-rs"
version.workspace = true
edition = "2024"
license = "GPL-3.0-or-later"
repository = "https://github.com/Lqm1/shiro-rs"
rust-version = "1.94"


description = "Speech alignment, feature extraction and HMM/HSMM training compatible with SHIRO"
readme = "README.md"
include = ["src/**", "examples/**", "Cargo.toml", "README.md", "LICENSE"]

[dependencies]
ciglet-rs = "0.1.0"
clap = { version = "4.6.7", features = ["derive", "error-context", "help", "std", "suggestions", "usage"], default-features = false }
liblrhsmm-rs = "0.1.0"
rand = { version = "0.10.3", default-features = false, features = ["std_rng"] }
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"
