#ifndef SHIRO_RS_H
#define SHIRO_RS_H

/* Generated by cbindgen. Do not edit manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * Independent owned f32 values; retrieve data through checked copies.
 */
typedef struct ShiroRsArrayF32 ShiroRsArrayF32;

/**
 * Independent owned u8 values; retrieve data through checked copies.
 */
typedef struct ShiroRsBytes ShiroRsBytes;

/**
 * Independent paired native observations and segmentations in sample order.
 */
typedef struct ShiroRsDataset ShiroRsDataset;

/**
 * Independent complete native model, including every stream and duration field.
 */
typedef struct ShiroRsModel ShiroRsModel;

/**
 * Independent native observation, including every stream and every frame.
 */
typedef struct ShiroRsObservation ShiroRsObservation;

/**
 * Independent complete state sequence, including jumps and extra JSON metadata.
 */
typedef struct ShiroRsStates ShiroRsStates;

/**
 * All native alignment settings. Integer flags must be 0 or 1. Layout follows
 * the target C ABI; duration_extra has the target size_t width.
 */
typedef struct ShiroRsAlignmentOptions {
  /**
   * 0 explicit HSMM durations, 1 geometric HMM durations.
   */
  uint32_t duration_mode;
  /**
   * 0 embedded alignment, 1 isolated phone groups.
   */
  uint32_t isolated;
  float hsmm_temperature;
  float duration_weight;
  float state_radius;
  uintptr_t duration_extra;
  float duration_extra_factor;
  float geometric_temperature;
  float pruning_slope;
} ShiroRsAlignmentOptions;

/**
 * All native initializer settings. Flags must be 0 or 1.
 */
typedef struct ShiroRsInitializationOptions {
  uint32_t flat_start;
  uint32_t globally_tied;
  float variance_floor_ratio;
} ShiroRsInitializationOptions;

/**
 * First revision of SHIRO's additive C interface.
 */
uint32_t shiro_rs_abi_version(void);

/**
 * Copy caller values into an independent owner, retaining all scalar bits.
 * # Safety
 * Borrowed buffers are aligned initialized storage valid for their stated
 * lengths. Owners have the declared type and remain live for the call. Outputs
 * are independent aligned writable storage; constructors use slots holding no
 * live owner. No buffer aliases participating owners. Mutation and release
 * require exclusive access; release transfers unique ownership and clears the
 * initialized slot. Empty buffers permit null pointers.
 */
uint32_t shiro_rs_bytes_create(const uint8_t *data, uintptr_t count, struct ShiroRsBytes **output);

/**
 * Copy the value count; errors retain the initialized output.
 * # Safety
 * Borrowed buffers are aligned initialized storage valid for their stated
 * lengths. Owners have the declared type and remain live for the call. Outputs
 * are independent aligned writable storage; constructors use slots holding no
 * live owner. No buffer aliases participating owners. Mutation and release
 * require exclusive access; release transfers unique ownership and clears the
 * initialized slot. Empty buffers permit null pointers.
 */
uint32_t shiro_rs_bytes_length(const struct ShiroRsBytes *handle, uintptr_t *output);

/**
 * Copy a checked contiguous range; errors leave caller buffers unchanged.
 * # Safety
 * Borrowed buffers are aligned initialized storage valid for their stated
 * lengths. Owners have the declared type and remain live for the call. Outputs
 * are independent aligned writable storage; constructors use slots holding no
 * live owner. No buffer aliases participating owners. Mutation and release
 * require exclusive access; release transfers unique ownership and clears the
 * initialized slot. Empty buffers permit null pointers.
 */
uint32_t shiro_rs_bytes_copy(const struct ShiroRsBytes *handle,
                             uintptr_t offset,
                             uint8_t *output,
                             uintptr_t count);

/**
 * Deep-copy all values; the copy outlives the source owner.
 * # Safety
 * Borrowed buffers are aligned initialized storage valid for their stated
 * lengths. Owners have the declared type and remain live for the call. Outputs
 * are independent aligned writable storage; constructors use slots holding no
 * live owner. No buffer aliases participating owners. Mutation and release
 * require exclusive access; release transfers unique ownership and clears the
 * initialized slot. Empty buffers permit null pointers.
 */
uint32_t shiro_rs_bytes_clone(const struct ShiroRsBytes *handle, struct ShiroRsBytes **output);

/**
 * Release unique ownership and clear its initialized slot. A null owned value is allowed.
 * # Safety
 * Borrowed buffers are aligned initialized storage valid for their stated
 * lengths. Owners have the declared type and remain live for the call. Outputs
 * are independent aligned writable storage; constructors use slots holding no
 * live owner. No buffer aliases participating owners. Mutation and release
 * require exclusive access; release transfers unique ownership and clears the
 * initialized slot. Empty buffers permit null pointers.
 */
uint32_t shiro_rs_bytes_release(struct ShiroRsBytes **owner);

/**
 * Copy caller values into an independent owner, retaining all scalar bits.
 * # Safety
 * Borrowed buffers are aligned initialized storage valid for their stated
 * lengths. Owners have the declared type and remain live for the call. Outputs
 * are independent aligned writable storage; constructors use slots holding no
 * live owner. No buffer aliases participating owners. Mutation and release
 * require exclusive access; release transfers unique ownership and clears the
 * initialized slot. Empty buffers permit null pointers.
 */
uint32_t shiro_rs_array_f32_create(const float *data,
                                   uintptr_t count,
                                   struct ShiroRsArrayF32 **output);

/**
 * Copy the value count; errors retain the initialized output.
 * # Safety
 * Borrowed buffers are aligned initialized storage valid for their stated
 * lengths. Owners have the declared type and remain live for the call. Outputs
 * are independent aligned writable storage; constructors use slots holding no
 * live owner. No buffer aliases participating owners. Mutation and release
 * require exclusive access; release transfers unique ownership and clears the
 * initialized slot. Empty buffers permit null pointers.
 */
uint32_t shiro_rs_array_f32_length(const struct ShiroRsArrayF32 *handle, uintptr_t *output);

/**
 * Copy a checked contiguous range; errors leave caller buffers unchanged.
 * # Safety
 * Borrowed buffers are aligned initialized storage valid for their stated
 * lengths. Owners have the declared type and remain live for the call. Outputs
 * are independent aligned writable storage; constructors use slots holding no
 * live owner. No buffer aliases participating owners. Mutation and release
 * require exclusive access; release transfers unique ownership and clears the
 * initialized slot. Empty buffers permit null pointers.
 */
uint32_t shiro_rs_array_f32_copy(const struct ShiroRsArrayF32 *handle,
                                 uintptr_t offset,
                                 float *output,
                                 uintptr_t count);

/**
 * Deep-copy all values; the copy outlives the source owner.
 * # Safety
 * Borrowed buffers are aligned initialized storage valid for their stated
 * lengths. Owners have the declared type and remain live for the call. Outputs
 * are independent aligned writable storage; constructors use slots holding no
 * live owner. No buffer aliases participating owners. Mutation and release
 * require exclusive access; release transfers unique ownership and clears the
 * initialized slot. Empty buffers permit null pointers.
 */
uint32_t shiro_rs_array_f32_clone(const struct ShiroRsArrayF32 *handle,
                                  struct ShiroRsArrayF32 **output);

/**
 * Release unique ownership and clear its initialized slot. A null owned value is allowed.
 * # Safety
 * Borrowed buffers are aligned initialized storage valid for their stated
 * lengths. Owners have the declared type and remain live for the call. Outputs
 * are independent aligned writable storage; constructors use slots holding no
 * live owner. No buffer aliases participating owners. Mutation and release
 * require exclusive access; release transfers unique ownership and clears the
 * initialized slot. Empty buffers permit null pointers.
 */
uint32_t shiro_rs_array_f32_release(struct ShiroRsArrayF32 **owner);

/**
 * Decode the original headerless little-endian binary32 stream with a scalar budget.
 * Partial final scalars and exceeded budgets retain initialized output slots.
 * # Safety
 * Borrowed buffers are aligned initialized storage valid for their stated
 * lengths. Owners have the declared type and remain live for the call. Outputs
 * are independent aligned writable storage; constructors use slots holding no
 * live owner. No buffer aliases participating owners. Mutation and release
 * require exclusive access; release transfers unique ownership and clears the
 * initialized slot. Empty buffers permit null pointers.
 */
uint32_t shiro_rs_rawfloat_read_bytes(const uint8_t *data,
                                      uintptr_t count,
                                      uintptr_t maximum_samples,
                                      struct ShiroRsArrayF32 **output);

/**
 * Encode all binary32 bits into independent original-format bytes.
 * # Safety
 * Borrowed buffers are aligned initialized storage valid for their stated
 * lengths. Owners have the declared type and remain live for the call. Outputs
 * are independent aligned writable storage; constructors use slots holding no
 * live owner. No buffer aliases participating owners. Mutation and release
 * require exclusive access; release transfers unique ownership and clears the
 * initialized slot. Empty buffers permit null pointers.
 */
uint32_t shiro_rs_rawfloat_write_bytes(const struct ShiroRsArrayF32 *handle,
                                       struct ShiroRsBytes **output);

/**
 * Build a model from the original UTF-8 JSON definition and its native defaults.
 * # Safety
 * Inputs are live owners created by this library. The output is independent,
 * aligned writable storage holding no live owner; it remains unchanged on error.
 */
uint32_t shiro_rs_model_from_definition(const struct ShiroRsBytes *definition,
                                        struct ShiroRsModel **output);

/**
 * Read a complete original model, reject trailing bytes and bound array entries.
 * Supports historical models with and without variance-floor fields.
 * # Safety
 * Input is a live owner created by this library. The output is independent,
 * aligned writable storage holding no live owner; it remains unchanged on error.
 */
uint32_t shiro_rs_model_read_bytes(const struct ShiroRsBytes *bytes,
                                   uintptr_t maximum_array_entries,
                                   struct ShiroRsModel **output);

/**
 * Write a complete original model. Encoding 0 includes variance floors; 1 omits
 * them and rejects nonzero floors instead of losing parameters. Other codes fail.
 * # Safety
 * Input is a live readable owner. The output is independent aligned writable
 * storage holding no live owner; it remains unchanged on error.
 */
uint32_t shiro_rs_model_write_bytes(const struct ShiroRsModel *model,
                                    uint32_t encoding,
                                    struct ShiroRsBytes **output);

/**
 * Clone every model parameter into independent storage.
 * # Safety
 * Input is a live readable owner. The output is independent aligned writable
 * storage holding no live owner; it remains unchanged on error.
 */
uint32_t shiro_rs_model_clone(const struct ShiroRsModel *model, struct ShiroRsModel **output);

/**
 * Release a unique model and clear its initialized slot. An empty slot succeeds.
 * # Safety
 * Slot is independent aligned writable storage containing a unique live model
 * from this library or null. No other call may use the model during release.
 */
uint32_t shiro_rs_model_release(struct ShiroRsModel **slot);

/**
 * Deinterleave original rawfloat bytes with explicitly supplied stream widths.
 * The frame budget and complete-frame validation are those of the native loader.
 * # Safety
 * Owners are live values from this library. Dimensions are initialized aligned
 * readable storage of the stated length. Output is independent aligned writable
 * storage holding no live owner. No writable storage aliases participating inputs.
 */
uint32_t shiro_rs_observation_read_rawfloat(const struct ShiroRsBytes *bytes,
                                            const uintptr_t *dimensions,
                                            uintptr_t stream_count,
                                            uintptr_t maximum_frames,
                                            struct ShiroRsObservation **output);

/**
 * Deinterleave rawfloat bytes using all stream dimensions of a complete model.
 * # Safety
 * Inputs are live readable owners from this library. Output is independent
 * aligned writable storage holding no live owner and remains unchanged on error.
 */
uint32_t shiro_rs_observation_from_model_rawfloat(const struct ShiroRsBytes *bytes,
                                                  const struct ShiroRsModel *model,
                                                  uintptr_t maximum_frames,
                                                  struct ShiroRsObservation **output);

/**
 * Serialize every observation field in the unchanged original MessagePack format.
 * # Safety
 * Input is a live readable owner. Output is independent aligned writable storage
 * holding no live owner and remains unchanged on error.
 */
uint32_t shiro_rs_observation_write_bytes(const struct ShiroRsObservation *observation,
                                          struct ShiroRsBytes **output);

/**
 * Deep-copy all observation fields; the clone survives release of the source.
 * # Safety
 * Input is a live readable owner. Output is independent aligned writable storage
 * holding no live owner and remains unchanged on error.
 */
uint32_t shiro_rs_observation_clone(const struct ShiroRsObservation *observation,
                                    struct ShiroRsObservation **output);

/**
 * Release a unique observation and clear its slot; an empty slot succeeds.
 * # Safety
 * Slot is aligned independent initialized writable storage holding a unique
 * live owner from this library or null. Release requires exclusive access.
 */
uint32_t shiro_rs_observation_release(struct ShiroRsObservation **slot);

/**
 * Parse a complete JSON array of native states, retaining all additional fields.
 * # Safety
 * Input is a live readable bytes owner. Output is independent aligned writable
 * storage holding no live owner and remains unchanged on error.
 */
uint32_t shiro_rs_states_read_json(const struct ShiroRsBytes *bytes, struct ShiroRsStates **output);

/**
 * Serialize every typed state field and flattened additional JSON metadata.
 * # Safety
 * Input is a live readable owner. Output is independent aligned writable storage
 * holding no live owner and remains unchanged on error.
 */
uint32_t shiro_rs_states_write_json(const struct ShiroRsStates *states,
                                    struct ShiroRsBytes **output);

/**
 * Deep-copy states, jumps, optional fields and all nested additional metadata.
 * # Safety
 * Input is a live readable owner. Output is independent aligned writable storage
 * holding no live owner and remains unchanged on error.
 */
uint32_t shiro_rs_states_clone(const struct ShiroRsStates *states, struct ShiroRsStates **output);

/**
 * Release a unique state sequence and clear its slot; an empty slot succeeds.
 * # Safety
 * Slot is aligned independent initialized writable storage holding a unique
 * live owner from this library or null. Release requires exclusive access.
 */
uint32_t shiro_rs_states_release(struct ShiroRsStates **slot);

/**
 * Construct and serialize the original segmentation from every state field.
 * Uses the native boundary conversion and transition residual arithmetic, and
 * retains both legacy MessagePack array-header mismatches for C readers.
 * # Safety
 * Inputs are live readable owners from this library. Output is independent
 * aligned writable storage holding no live owner and remains unchanged on error.
 */
uint32_t shiro_rs_states_segmentation_bytes(const struct ShiroRsStates *states,
                                            const struct ShiroRsModel *model,
                                            struct ShiroRsBytes **output);

/**
 * Copy the unchanged native defaults into caller-provided descriptor storage.
 * # Safety
 * Output is independent aligned exclusively writable storage for one descriptor.
 */
uint32_t shiro_rs_alignment_options_default(struct ShiroRsAlignmentOptions *output);

/**
 * Align all input states without modifying any participating input owner.
 * # Safety
 * Inputs are live readable owners from this library. Options are aligned live
 * initialized readable descriptor storage. Output is independent aligned writable
 * storage holding no live owner and remains unchanged on failure. No participating
 * owner or descriptor may be modified or released during this call.
 */
uint32_t shiro_rs_align_states(const struct ShiroRsModel *model,
                               const struct ShiroRsObservation *observation,
                               const struct ShiroRsStates *states,
                               const struct ShiroRsAlignmentOptions *options,
                               struct ShiroRsStates **output);

/**
 * Align a complete original JSON document using the unchanged native file loader.
 * Filenames retain their process-relative meaning. All document, file and state
 * metadata is retained. Output is complete UTF-8 JSON in independent storage.
 * # Safety
 * Inputs are live readable owners from this library. Options are aligned live
 * initialized readable descriptor storage. Output is independent aligned writable
 * storage holding no live owner and remains unchanged on failure. No participating
 * owner or descriptor may be modified or released during this call.
 */
uint32_t shiro_rs_align_document(const struct ShiroRsModel *model,
                                 const struct ShiroRsBytes *document,
                                 const struct ShiroRsAlignmentOptions *options,
                                 struct ShiroRsBytes **output);

/**
 * Deep-copy all observations and convert all state sequences using the model.
 * Repeated owners are allowed; empty inputs create an empty paired dataset.
 * # Safety
 * Model and every array element are live readable owners from this library.
 * Arrays are aligned initialized readable storage of sample_count elements.
 * Output is independent aligned writable storage holding no live owner on success.
 * Inputs remain unchanged; failed calls retain the initialized output slot.
 */
uint32_t shiro_rs_dataset_create(const struct ShiroRsModel *model,
                                 const struct ShiroRsObservation *const *observations,
                                 const struct ShiroRsStates *const *states,
                                 uintptr_t sample_count,
                                 struct ShiroRsDataset **output);

/**
 * Load a complete original JSON document with unchanged native filename/frame
 * semantics. All samples remain paired in document order.
 * # Safety
 * Inputs are live readable owners. Output is independent aligned writable storage
 * holding no live owner on success. Inputs and failed output slots remain unchanged.
 */
uint32_t shiro_rs_dataset_read_document(const struct ShiroRsModel *model,
                                        const struct ShiroRsBytes *document,
                                        uintptr_t maximum_frames,
                                        struct ShiroRsDataset **output);

/**
 * Retrieve the paired sample count without borrowing internal storage.
 * # Safety
 * Input is a live readable owner and output is independent aligned writable storage.
 */
uint32_t shiro_rs_dataset_length(const struct ShiroRsDataset *dataset, uintptr_t *output);

/**
 * Retrieve a complete independent observation snapshot by sample index.
 * # Safety
 * Input is a live readable owner. Output is independent aligned writable storage
 * holding no live owner on success. Failed outputs remain unchanged.
 */
uint32_t shiro_rs_dataset_get_observation(const struct ShiroRsDataset *dataset,
                                          uintptr_t index,
                                          struct ShiroRsObservation **output);

/**
 * Serialize every field of one complete segmentation in the original format.
 * # Safety
 * Input is a live readable owner. Output is independent aligned writable storage
 * holding no live owner on success. Failed outputs remain unchanged.
 */
uint32_t shiro_rs_dataset_get_segmentation_bytes(const struct ShiroRsDataset *dataset,
                                                 uintptr_t index,
                                                 struct ShiroRsBytes **output);

/**
 * Deep-copy the complete paired dataset, retaining every scalar bit.
 * # Safety
 * Input is a live readable owner. Output is independent aligned writable storage
 * holding no live owner on success. Failed outputs remain unchanged.
 */
uint32_t shiro_rs_dataset_clone(const struct ShiroRsDataset *dataset,
                                struct ShiroRsDataset **output);

/**
 * Release a unique dataset and clear its slot. An empty slot succeeds.
 * # Safety
 * Slot is independent aligned initialized writable storage holding a unique live
 * owner from this library or null. Release requires exclusive access.
 */
uint32_t shiro_rs_dataset_release(struct ShiroRsDataset **slot);

/**
 * Copy the unchanged native initializer defaults into caller storage.
 * # Safety
 * Output is independent aligned exclusively writable descriptor storage.
 */
uint32_t shiro_rs_initialization_options_default(struct ShiroRsInitializationOptions *output);

/**
 * Initialize all model parameters from the complete paired dataset. Inputs are
 * never modified; native corpus fallback/tied/flat rounding corrections apply.
 * # Safety
 * Inputs are live readable owners and options are aligned initialized readable
 * descriptor storage. Output is independent aligned writable storage holding no
 * live owner on success. Failed outputs remain unchanged.
 */
uint32_t shiro_rs_initialize(const struct ShiroRsModel *model,
                             const struct ShiroRsDataset *dataset,
                             const struct ShiroRsInitializationOptions *options,
                             struct ShiroRsModel **output);

#endif  /* SHIRO_RS_H */
