#ifndef SHIRO_RS_H
#define SHIRO_RS_H

/* Generated by cbindgen. Do not edit manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * Independent owned f32 values; retrieve data through checked copies.
 */
typedef struct ShiroRsArrayF32 ShiroRsArrayF32;

/**
 * Independently owned target-width unsigned integers.
 */
typedef struct ShiroRsArrayUsize ShiroRsArrayUsize;

/**
 * Independent owned u8 values; retrieve data through checked copies.
 */
typedef struct ShiroRsBytes ShiroRsBytes;

/**
 * Independent paired native observations and segmentations in sample order.
 */
typedef struct ShiroRsDataset ShiroRsDataset;

/**
 * Independent complete groups in original order.
 */
typedef struct ShiroRsIsolatedGroups ShiroRsIsolatedGroups;

/**
 * Complete report. Callback reports are borrowed only for the callback; clone
 * before retaining one. Only constructor/getter/clone results may be released.
 */
typedef struct ShiroRsIterationReport ShiroRsIterationReport;

/**
 * Independent complete timed labels in original order.
 */
typedef struct ShiroRsLabels ShiroRsLabels;

/**
 * Independent complete native model, including every stream and duration field.
 */
typedef struct ShiroRsModel ShiroRsModel;

/**
 * Independent native observation, including every stream and every frame.
 */
typedef struct ShiroRsObservation ShiroRsObservation;

/**
 * Independent complete phone map, including flattened JSON attributes.
 */
typedef struct ShiroRsPhoneMap ShiroRsPhoneMap;

/**
 * Independent complete state sequence, including jumps and extra JSON metadata.
 */
typedef struct ShiroRsStates ShiroRsStates;

/**
 * Independent ordered datasets, one per original file; each retains its groups.
 */
typedef struct ShiroRsTrainingFiles ShiroRsTrainingFiles;

/**
 * Independent complete trained model and every ordered iteration report.
 */
typedef struct ShiroRsTrainingResult ShiroRsTrainingResult;

/**
 * Independent complete model, segmentation document and assignment table.
 */
typedef struct ShiroRsUntiedModel ShiroRsUntiedModel;

/**
 * All native alignment settings. Integer flags must be 0 or 1. Layout follows
 * the target C ABI; duration_extra has the target size_t width.
 */
typedef struct ShiroRsAlignmentOptions {
  /**
   * 0 explicit HSMM durations, 1 geometric HMM durations.
   */
  uint32_t duration_mode;
  /**
   * 0 embedded alignment, 1 isolated phone groups.
   */
  uint32_t isolated;
  float hsmm_temperature;
  float duration_weight;
  float state_radius;
  uintptr_t duration_extra;
  float duration_extra_factor;
  float geometric_temperature;
  float pruning_slope;
} ShiroRsAlignmentOptions;

/**
 * All native initializer settings. Flags must be 0 or 1.
 */
typedef struct ShiroRsInitializationOptions {
  uint32_t flat_start;
  uint32_t globally_tied;
  float variance_floor_ratio;
} ShiroRsInitializationOptions;

/**
 * All native training options. Flags/mode must be0/1; native numeric validation
 * and per-iteration annealing temperature replacement remain unchanged.
 */
typedef struct ShiroRsTrainingOptions {
  uintptr_t iterations;
  /**
   * 0 normal HSMM durations,1 geometric HMM durations.
   */
  uint32_t duration_mode;
  float hsmm_temperature;
  float duration_weight;
  float state_radius;
  uintptr_t duration_extra;
  float duration_extra_factor;
  float geometric_temperature;
  float pruning_slope;
  float termination_threshold;
  uint32_t deterministic_annealing;
  uint32_t mean_frame_likelihood;
  uintptr_t workers;
} ShiroRsTrainingOptions;

/**
 * Synchronous progress callback. Report is read-only and live only for this call.
 * It may be queried or cloned, but must not be released or retained un-cloned.
 * Callback must return normally without exceptions/unwinding across the C ABI;
 * participating training input owners must not be mutated or released.
 */
typedef void (*ShiroRsProgressCallback)(void*, const struct ShiroRsIterationReport*);

/**
 * Exact native scalar report fields; nested file rows are retrieved separately.
 */
typedef struct ShiroRsIterationInfo {
  uintptr_t iteration;
  float temperature;
  float mean_log_likelihood;
} ShiroRsIterationInfo;

/**
 * Native phone expansion counts and flag. Topology is a separate optional UTF-8
 * byte owner so an absent topology remains distinct from an empty string.
 */
typedef struct ShiroRsPhoneOptions {
  uintptr_t states_per_phone;
  uintptr_t streams;
  /**
   * Zero disables weak skips; one enables them. Other codes are invalid.
   */
  uint32_t weak_skips;
} ShiroRsPhoneOptions;

/**
 * Complete caller-supplied label. Name is a live readable UTF-8 byte owner.
 */
typedef struct ShiroRsLabelInput {
  double start;
  double end;
  const struct ShiroRsBytes *name;
} ShiroRsLabelInput;

/**
 * Exact binary64 label times; names are retrieved as independent byte owners.
 */
typedef struct ShiroRsLabelInfo {
  double start;
  double end;
} ShiroRsLabelInfo;

/**
 * All native assignment fields in target-width integer representation.
 */
typedef struct ShiroRsAssignment {
  uintptr_t state;
  uintptr_t file;
  uintptr_t segment;
} ShiroRsAssignment;

/**
 * Every field needed to construct a native group. Owners are borrowed only
 * during construction; the collection deep-copies observation and state data.
 */
typedef struct ShiroRsIsolatedGroupInput {
  uintptr_t first_state;
  uintptr_t first_frame;
  const struct ShiroRsObservation *observation;
  const struct ShiroRsStates *states;
} ShiroRsIsolatedGroupInput;

/**
 * Both original target-width position fields of an isolated group.
 */
typedef struct ShiroRsIsolatedGroupInfo {
  uintptr_t first_state;
  uintptr_t first_frame;
} ShiroRsIsolatedGroupInfo;

/**
 * First revision of SHIRO's additive C interface.
 */
uint32_t shiro_rs_abi_version(void);

/**
 * Copy caller values into an independent owner, retaining all scalar bits.
 * # Safety
 * Borrowed buffers are aligned initialized storage valid for their stated
 * lengths. Owners have the declared type and remain live for the call. Outputs
 * are independent aligned writable storage; constructors use slots holding no
 * live owner. No buffer aliases participating owners. Mutation and release
 * require exclusive access; release transfers unique ownership and clears the
 * initialized slot. Empty buffers permit null pointers.
 */
uint32_t shiro_rs_bytes_create(const uint8_t *data, uintptr_t count, struct ShiroRsBytes **output);

/**
 * Copy the value count; errors retain the initialized output.
 * # Safety
 * Borrowed buffers are aligned initialized storage valid for their stated
 * lengths. Owners have the declared type and remain live for the call. Outputs
 * are independent aligned writable storage; constructors use slots holding no
 * live owner. No buffer aliases participating owners. Mutation and release
 * require exclusive access; release transfers unique ownership and clears the
 * initialized slot. Empty buffers permit null pointers.
 */
uint32_t shiro_rs_bytes_length(const struct ShiroRsBytes *handle, uintptr_t *output);

/**
 * Copy a checked contiguous range; errors leave caller buffers unchanged.
 * # Safety
 * Borrowed buffers are aligned initialized storage valid for their stated
 * lengths. Owners have the declared type and remain live for the call. Outputs
 * are independent aligned writable storage; constructors use slots holding no
 * live owner. No buffer aliases participating owners. Mutation and release
 * require exclusive access; release transfers unique ownership and clears the
 * initialized slot. Empty buffers permit null pointers.
 */
uint32_t shiro_rs_bytes_copy(const struct ShiroRsBytes *handle,
                             uintptr_t offset,
                             uint8_t *output,
                             uintptr_t count);

/**
 * Deep-copy all values; the copy outlives the source owner.
 * # Safety
 * Borrowed buffers are aligned initialized storage valid for their stated
 * lengths. Owners have the declared type and remain live for the call. Outputs
 * are independent aligned writable storage; constructors use slots holding no
 * live owner. No buffer aliases participating owners. Mutation and release
 * require exclusive access; release transfers unique ownership and clears the
 * initialized slot. Empty buffers permit null pointers.
 */
uint32_t shiro_rs_bytes_clone(const struct ShiroRsBytes *handle, struct ShiroRsBytes **output);

/**
 * Release unique ownership and clear its initialized slot. A null owned value is allowed.
 * # Safety
 * Borrowed buffers are aligned initialized storage valid for their stated
 * lengths. Owners have the declared type and remain live for the call. Outputs
 * are independent aligned writable storage; constructors use slots holding no
 * live owner. No buffer aliases participating owners. Mutation and release
 * require exclusive access; release transfers unique ownership and clears the
 * initialized slot. Empty buffers permit null pointers.
 */
uint32_t shiro_rs_bytes_release(struct ShiroRsBytes **owner);

/**
 * Copy caller values into an independent owner, retaining all scalar bits.
 * # Safety
 * Borrowed buffers are aligned initialized storage valid for their stated
 * lengths. Owners have the declared type and remain live for the call. Outputs
 * are independent aligned writable storage; constructors use slots holding no
 * live owner. No buffer aliases participating owners. Mutation and release
 * require exclusive access; release transfers unique ownership and clears the
 * initialized slot. Empty buffers permit null pointers.
 */
uint32_t shiro_rs_array_f32_create(const float *data,
                                   uintptr_t count,
                                   struct ShiroRsArrayF32 **output);

/**
 * Copy the value count; errors retain the initialized output.
 * # Safety
 * Borrowed buffers are aligned initialized storage valid for their stated
 * lengths. Owners have the declared type and remain live for the call. Outputs
 * are independent aligned writable storage; constructors use slots holding no
 * live owner. No buffer aliases participating owners. Mutation and release
 * require exclusive access; release transfers unique ownership and clears the
 * initialized slot. Empty buffers permit null pointers.
 */
uint32_t shiro_rs_array_f32_length(const struct ShiroRsArrayF32 *handle, uintptr_t *output);

/**
 * Copy a checked contiguous range; errors leave caller buffers unchanged.
 * # Safety
 * Borrowed buffers are aligned initialized storage valid for their stated
 * lengths. Owners have the declared type and remain live for the call. Outputs
 * are independent aligned writable storage; constructors use slots holding no
 * live owner. No buffer aliases participating owners. Mutation and release
 * require exclusive access; release transfers unique ownership and clears the
 * initialized slot. Empty buffers permit null pointers.
 */
uint32_t shiro_rs_array_f32_copy(const struct ShiroRsArrayF32 *handle,
                                 uintptr_t offset,
                                 float *output,
                                 uintptr_t count);

/**
 * Deep-copy all values; the copy outlives the source owner.
 * # Safety
 * Borrowed buffers are aligned initialized storage valid for their stated
 * lengths. Owners have the declared type and remain live for the call. Outputs
 * are independent aligned writable storage; constructors use slots holding no
 * live owner. No buffer aliases participating owners. Mutation and release
 * require exclusive access; release transfers unique ownership and clears the
 * initialized slot. Empty buffers permit null pointers.
 */
uint32_t shiro_rs_array_f32_clone(const struct ShiroRsArrayF32 *handle,
                                  struct ShiroRsArrayF32 **output);

/**
 * Release unique ownership and clear its initialized slot. A null owned value is allowed.
 * # Safety
 * Borrowed buffers are aligned initialized storage valid for their stated
 * lengths. Owners have the declared type and remain live for the call. Outputs
 * are independent aligned writable storage; constructors use slots holding no
 * live owner. No buffer aliases participating owners. Mutation and release
 * require exclusive access; release transfers unique ownership and clears the
 * initialized slot. Empty buffers permit null pointers.
 */
uint32_t shiro_rs_array_f32_release(struct ShiroRsArrayF32 **owner);

/**
 * Decode the original headerless little-endian binary32 stream with a scalar budget.
 * Partial final scalars and exceeded budgets retain initialized output slots.
 * # Safety
 * Borrowed buffers are aligned initialized storage valid for their stated
 * lengths. Owners have the declared type and remain live for the call. Outputs
 * are independent aligned writable storage; constructors use slots holding no
 * live owner. No buffer aliases participating owners. Mutation and release
 * require exclusive access; release transfers unique ownership and clears the
 * initialized slot. Empty buffers permit null pointers.
 */
uint32_t shiro_rs_rawfloat_read_bytes(const uint8_t *data,
                                      uintptr_t count,
                                      uintptr_t maximum_samples,
                                      struct ShiroRsArrayF32 **output);

/**
 * Encode all binary32 bits into independent original-format bytes.
 * # Safety
 * Borrowed buffers are aligned initialized storage valid for their stated
 * lengths. Owners have the declared type and remain live for the call. Outputs
 * are independent aligned writable storage; constructors use slots holding no
 * live owner. No buffer aliases participating owners. Mutation and release
 * require exclusive access; release transfers unique ownership and clears the
 * initialized slot. Empty buffers permit null pointers.
 */
uint32_t shiro_rs_rawfloat_write_bytes(const struct ShiroRsArrayF32 *handle,
                                       struct ShiroRsBytes **output);

/**
 * Build a model from the original UTF-8 JSON definition and its native defaults.
 * # Safety
 * Inputs are live owners created by this library. The output is independent,
 * aligned writable storage holding no live owner; it remains unchanged on error.
 */
uint32_t shiro_rs_model_from_definition(const struct ShiroRsBytes *definition,
                                        struct ShiroRsModel **output);

/**
 * Read a complete original model, reject trailing bytes and bound array entries.
 * Supports historical models with and without variance-floor fields.
 * # Safety
 * Input is a live owner created by this library. The output is independent,
 * aligned writable storage holding no live owner; it remains unchanged on error.
 */
uint32_t shiro_rs_model_read_bytes(const struct ShiroRsBytes *bytes,
                                   uintptr_t maximum_array_entries,
                                   struct ShiroRsModel **output);

/**
 * Write a complete original model. Encoding 0 includes variance floors; 1 omits
 * them and rejects nonzero floors instead of losing parameters. Other codes fail.
 * # Safety
 * Input is a live readable owner. The output is independent aligned writable
 * storage holding no live owner; it remains unchanged on error.
 */
uint32_t shiro_rs_model_write_bytes(const struct ShiroRsModel *model,
                                    uint32_t encoding,
                                    struct ShiroRsBytes **output);

/**
 * Clone every model parameter into independent storage.
 * # Safety
 * Input is a live readable owner. The output is independent aligned writable
 * storage holding no live owner; it remains unchanged on error.
 */
uint32_t shiro_rs_model_clone(const struct ShiroRsModel *model, struct ShiroRsModel **output);

/**
 * Release a unique model and clear its initialized slot. An empty slot succeeds.
 * # Safety
 * Slot is independent aligned writable storage containing a unique live model
 * from this library or null. No other call may use the model during release.
 */
uint32_t shiro_rs_model_release(struct ShiroRsModel **slot);

/**
 * Deinterleave original rawfloat bytes with explicitly supplied stream widths.
 * The frame budget and complete-frame validation are those of the native loader.
 * # Safety
 * Owners are live values from this library. Dimensions are initialized aligned
 * readable storage of the stated length. Output is independent aligned writable
 * storage holding no live owner. No writable storage aliases participating inputs.
 */
uint32_t shiro_rs_observation_read_rawfloat(const struct ShiroRsBytes *bytes,
                                            const uintptr_t *dimensions,
                                            uintptr_t stream_count,
                                            uintptr_t maximum_frames,
                                            struct ShiroRsObservation **output);

/**
 * Deinterleave rawfloat bytes using all stream dimensions of a complete model.
 * # Safety
 * Inputs are live readable owners from this library. Output is independent
 * aligned writable storage holding no live owner and remains unchanged on error.
 */
uint32_t shiro_rs_observation_from_model_rawfloat(const struct ShiroRsBytes *bytes,
                                                  const struct ShiroRsModel *model,
                                                  uintptr_t maximum_frames,
                                                  struct ShiroRsObservation **output);

/**
 * Serialize every observation field in the unchanged original MessagePack format.
 * # Safety
 * Input is a live readable owner. Output is independent aligned writable storage
 * holding no live owner and remains unchanged on error.
 */
uint32_t shiro_rs_observation_write_bytes(const struct ShiroRsObservation *observation,
                                          struct ShiroRsBytes **output);

/**
 * Deep-copy all observation fields; the clone survives release of the source.
 * # Safety
 * Input is a live readable owner. Output is independent aligned writable storage
 * holding no live owner and remains unchanged on error.
 */
uint32_t shiro_rs_observation_clone(const struct ShiroRsObservation *observation,
                                    struct ShiroRsObservation **output);

/**
 * Release a unique observation and clear its slot; an empty slot succeeds.
 * # Safety
 * Slot is aligned independent initialized writable storage holding a unique
 * live owner from this library or null. Release requires exclusive access.
 */
uint32_t shiro_rs_observation_release(struct ShiroRsObservation **slot);

/**
 * Parse a complete JSON array of native states, retaining all additional fields.
 * # Safety
 * Input is a live readable bytes owner. Output is independent aligned writable
 * storage holding no live owner and remains unchanged on error.
 */
uint32_t shiro_rs_states_read_json(const struct ShiroRsBytes *bytes, struct ShiroRsStates **output);

/**
 * Serialize every typed state field and flattened additional JSON metadata.
 * # Safety
 * Input is a live readable owner. Output is independent aligned writable storage
 * holding no live owner and remains unchanged on error.
 */
uint32_t shiro_rs_states_write_json(const struct ShiroRsStates *states,
                                    struct ShiroRsBytes **output);

/**
 * Deep-copy states, jumps, optional fields and all nested additional metadata.
 * # Safety
 * Input is a live readable owner. Output is independent aligned writable storage
 * holding no live owner and remains unchanged on error.
 */
uint32_t shiro_rs_states_clone(const struct ShiroRsStates *states, struct ShiroRsStates **output);

/**
 * Release a unique state sequence and clear its slot; an empty slot succeeds.
 * # Safety
 * Slot is aligned independent initialized writable storage holding a unique
 * live owner from this library or null. Release requires exclusive access.
 */
uint32_t shiro_rs_states_release(struct ShiroRsStates **slot);

/**
 * Construct and serialize the original segmentation from every state field.
 * Uses the native boundary conversion and transition residual arithmetic, and
 * retains both legacy MessagePack array-header mismatches for C readers.
 * # Safety
 * Inputs are live readable owners from this library. Output is independent
 * aligned writable storage holding no live owner and remains unchanged on error.
 */
uint32_t shiro_rs_states_segmentation_bytes(const struct ShiroRsStates *states,
                                            const struct ShiroRsModel *model,
                                            struct ShiroRsBytes **output);

/**
 * Copy the unchanged native defaults into caller-provided descriptor storage.
 * # Safety
 * Output is independent aligned exclusively writable storage for one descriptor.
 */
uint32_t shiro_rs_alignment_options_default(struct ShiroRsAlignmentOptions *output);

/**
 * Align all input states without modifying any participating input owner.
 * # Safety
 * Inputs are live readable owners from this library. Options are aligned live
 * initialized readable descriptor storage. Output is independent aligned writable
 * storage holding no live owner and remains unchanged on failure. No participating
 * owner or descriptor may be modified or released during this call.
 */
uint32_t shiro_rs_align_states(const struct ShiroRsModel *model,
                               const struct ShiroRsObservation *observation,
                               const struct ShiroRsStates *states,
                               const struct ShiroRsAlignmentOptions *options,
                               struct ShiroRsStates **output);

/**
 * Align a complete original JSON document using the unchanged native file loader.
 * Filenames retain their process-relative meaning. All document, file and state
 * metadata is retained. Output is complete UTF-8 JSON in independent storage.
 * # Safety
 * Inputs are live readable owners from this library. Options are aligned live
 * initialized readable descriptor storage. Output is independent aligned writable
 * storage holding no live owner and remains unchanged on failure. No participating
 * owner or descriptor may be modified or released during this call.
 */
uint32_t shiro_rs_align_document(const struct ShiroRsModel *model,
                                 const struct ShiroRsBytes *document,
                                 const struct ShiroRsAlignmentOptions *options,
                                 struct ShiroRsBytes **output);

/**
 * Deep-copy all observations and convert all state sequences using the model.
 * Repeated owners are allowed; empty inputs create an empty paired dataset.
 * # Safety
 * Model and every array element are live readable owners from this library.
 * Arrays are aligned initialized readable storage of sample_count elements.
 * Output is independent aligned writable storage holding no live owner on success.
 * Inputs remain unchanged; failed calls retain the initialized output slot.
 */
uint32_t shiro_rs_dataset_create(const struct ShiroRsModel *model,
                                 const struct ShiroRsObservation *const *observations,
                                 const struct ShiroRsStates *const *states,
                                 uintptr_t sample_count,
                                 struct ShiroRsDataset **output);

/**
 * Load a complete original JSON document with unchanged native filename/frame
 * semantics. All samples remain paired in document order.
 * # Safety
 * Inputs are live readable owners. Output is independent aligned writable storage
 * holding no live owner on success. Inputs and failed output slots remain unchanged.
 */
uint32_t shiro_rs_dataset_read_document(const struct ShiroRsModel *model,
                                        const struct ShiroRsBytes *document,
                                        uintptr_t maximum_frames,
                                        struct ShiroRsDataset **output);

/**
 * Retrieve the paired sample count without borrowing internal storage.
 * # Safety
 * Input is a live readable owner and output is independent aligned writable storage.
 */
uint32_t shiro_rs_dataset_length(const struct ShiroRsDataset *dataset, uintptr_t *output);

/**
 * Retrieve a complete independent observation snapshot by sample index.
 * # Safety
 * Input is a live readable owner. Output is independent aligned writable storage
 * holding no live owner on success. Failed outputs remain unchanged.
 */
uint32_t shiro_rs_dataset_get_observation(const struct ShiroRsDataset *dataset,
                                          uintptr_t index,
                                          struct ShiroRsObservation **output);

/**
 * Serialize every field of one complete segmentation in the original format.
 * # Safety
 * Input is a live readable owner. Output is independent aligned writable storage
 * holding no live owner on success. Failed outputs remain unchanged.
 */
uint32_t shiro_rs_dataset_get_segmentation_bytes(const struct ShiroRsDataset *dataset,
                                                 uintptr_t index,
                                                 struct ShiroRsBytes **output);

/**
 * Deep-copy the complete paired dataset, retaining every scalar bit.
 * # Safety
 * Input is a live readable owner. Output is independent aligned writable storage
 * holding no live owner on success. Failed outputs remain unchanged.
 */
uint32_t shiro_rs_dataset_clone(const struct ShiroRsDataset *dataset,
                                struct ShiroRsDataset **output);

/**
 * Release a unique dataset and clear its slot. An empty slot succeeds.
 * # Safety
 * Slot is independent aligned initialized writable storage holding a unique live
 * owner from this library or null. Release requires exclusive access.
 */
uint32_t shiro_rs_dataset_release(struct ShiroRsDataset **slot);

/**
 * Copy the unchanged native initializer defaults into caller storage.
 * # Safety
 * Output is independent aligned exclusively writable descriptor storage.
 */
uint32_t shiro_rs_initialization_options_default(struct ShiroRsInitializationOptions *output);

/**
 * Initialize all model parameters from the complete paired dataset. Inputs are
 * never modified; native corpus fallback/tied/flat rounding corrections apply.
 * # Safety
 * Inputs are live readable owners and options are aligned initialized readable
 * descriptor storage. Output is independent aligned writable storage holding no
 * live owner on success. Failed outputs remain unchanged.
 */
uint32_t shiro_rs_initialize(const struct ShiroRsModel *model,
                             const struct ShiroRsDataset *dataset,
                             const struct ShiroRsInitializationOptions *options,
                             struct ShiroRsModel **output);

/**
 * Clone complete paired datasets into independent file order. Repeated and empty
 * inputs are permitted; native training validates their applicability.
 * # Safety
 * Array is aligned initialized readable storage of count live owners from this
 * library. Output is independent aligned writable storage holding no live owner
 * on success. Inputs and failed outputs remain unchanged.
 */
uint32_t shiro_rs_training_files_create(const struct ShiroRsDataset *const *files,
                                        uintptr_t count,
                                        struct ShiroRsTrainingFiles **output);

/**
 * Load one complete paired dataset per original file, preserving isolated groups
 * and file order via the unchanged native host loader. isolated must be0/1.
 * # Safety
 * Inputs are live readable owners. Output is independent aligned writable storage
 * holding no live owner on success. Inputs and failed outputs remain unchanged.
 */
uint32_t shiro_rs_training_files_read_document(const struct ShiroRsModel *model,
                                               const struct ShiroRsBytes *document,
                                               uintptr_t maximum_frames,
                                               uint32_t isolated,
                                               struct ShiroRsTrainingFiles **output);

/**
 * Retrieve the ordered file count.
 * # Safety
 * Input is a live readable owner; output is independent aligned writable storage.
 */
uint32_t shiro_rs_training_files_length(const struct ShiroRsTrainingFiles *files,
                                        uintptr_t *output);

/**
 * Deep-copy one complete paired dataset, retaining all groups and scalar bits.
 * # Safety
 * Input is a live readable owner; output is independent aligned writable storage
 * holding no live owner on success. Failed outputs remain unchanged.
 */
uint32_t shiro_rs_training_files_get_dataset(const struct ShiroRsTrainingFiles *files,
                                             uintptr_t index,
                                             struct ShiroRsDataset **output);

/**
 * Deep-copy every ordered file and group.
 * # Safety
 * Input is a live readable owner; output is independent aligned writable storage
 * holding no live owner on success. Failed outputs remain unchanged.
 */
uint32_t shiro_rs_training_files_clone(const struct ShiroRsTrainingFiles *files,
                                       struct ShiroRsTrainingFiles **output);

/**
 * Release unique files and clear their slot; empty slot succeeds.
 * # Safety
 * Slot is independent aligned writable storage holding a unique live owner or
 * null. Release requires exclusive access and transfers ownership to this library.
 */
uint32_t shiro_rs_training_files_release(struct ShiroRsTrainingFiles **slot);

/**
 * Copy every unchanged native training default into the descriptor.
 * # Safety
 * Output is independent aligned exclusively writable descriptor storage.
 */
uint32_t shiro_rs_training_options_default(struct ShiroRsTrainingOptions *output);

/**
 * Train with every native setting, retaining all reports and the complete model.
 * # Safety
 * Inputs are live readable owners and options are initialized readable descriptor
 * storage. Output is independent aligned writable storage holding no live owner
 * on success. Inputs and failed output slots remain unchanged.
 */
uint32_t shiro_rs_train(const struct ShiroRsModel *model,
                        const struct ShiroRsTrainingFiles *files,
                        const struct ShiroRsTrainingOptions *options,
                        struct ShiroRsTrainingResult **output);

/**
 * Train with synchronous progress after each model update and before report
 * storage/stopping checks. Notifications already delivered are not rolled back
 * if a later iteration fails. Null callback means no notifications.
 * # Safety
 * Inputs/options/output obey train's contract. Callback and context remain valid
 * throughout the call and obey ShiroRsProgressCallback's borrowed-lifetime/no-unwind
 * contract. Callback must not mutate/release participating training inputs.
 */
uint32_t shiro_rs_train_with_progress(const struct ShiroRsModel *model,
                                      const struct ShiroRsTrainingFiles *files,
                                      const struct ShiroRsTrainingOptions *options,
                                      ShiroRsProgressCallback callback,
                                      void *context,
                                      struct ShiroRsTrainingResult **output);

/**
 * Retrieve the number of completed ordered iteration reports.
 * # Safety
 * Input is a live readable owner and output is independent aligned writable storage.
 */
uint32_t shiro_rs_training_result_length(const struct ShiroRsTrainingResult *training,
                                         uintptr_t *output);

/**
 * Deep-copy every trained model parameter into independent storage.
 * # Safety
 * Input is a live readable owner. Output is independent aligned writable storage
 * holding no live owner on success. Failed outputs remain unchanged.
 */
uint32_t shiro_rs_training_result_get_model(const struct ShiroRsTrainingResult *training,
                                            struct ShiroRsModel **output);

/**
 * Deep-copy a complete report, including every ordered file/group likelihood.
 * # Safety
 * Input is a live readable owner. Output is independent aligned writable storage
 * holding no live owner on success. Failed outputs remain unchanged.
 */
uint32_t shiro_rs_training_result_get_report(const struct ShiroRsTrainingResult *training,
                                             uintptr_t index,
                                             struct ShiroRsIterationReport **output);

/**
 * Deep-copy the complete model and every nested report field.
 * # Safety
 * Input is a live readable owner. Output is independent aligned writable storage
 * holding no live owner on success. Failed outputs remain unchanged.
 */
uint32_t shiro_rs_training_result_clone(const struct ShiroRsTrainingResult *training,
                                        struct ShiroRsTrainingResult **output);

/**
 * Release a unique training result and clear its slot; empty slot succeeds.
 * # Safety
 * Slot is independent aligned writable storage holding a unique live owner or
 * null. Release requires exclusive access and transfers ownership to this library.
 */
uint32_t shiro_rs_training_result_release(struct ShiroRsTrainingResult **slot);

/**
 * Copy all exact native scalar report fields. Callback reports may be queried.
 * # Safety
 * Input is a live readable owned report or a live callback-borrowed report.
 * Output is independent aligned writable descriptor storage.
 */
uint32_t shiro_rs_iteration_report_info(const struct ShiroRsIterationReport *report,
                                        struct ShiroRsIterationInfo *output);

/**
 * Retrieve the original file count, retaining nested group boundaries.
 * # Safety
 * Input is a live readable owned/callback-borrowed report. Output is independent
 * aligned writable storage.
 */
uint32_t shiro_rs_iteration_report_file_count(const struct ShiroRsIterationReport *report,
                                              uintptr_t *output);

/**
 * Copy the complete binary32 group likelihood row for one original file.
 * # Safety
 * Input is a live readable owned/callback-borrowed report. Output is independent
 * aligned writable storage holding no live owner on success; failures retain it.
 */
uint32_t shiro_rs_iteration_report_get_file(const struct ShiroRsIterationReport *report,
                                            uintptr_t index,
                                            struct ShiroRsArrayF32 **output);

/**
 * Clone a complete owned or callback-borrowed report into independent ownership.
 * # Safety
 * Input is a live readable owned/callback-borrowed report. Output is independent
 * aligned writable storage holding no live owner on success; failures retain it.
 */
uint32_t shiro_rs_iteration_report_clone(const struct ShiroRsIterationReport *report,
                                         struct ShiroRsIterationReport **output);

/**
 * Release a unique owned report and clear its slot; never release a callback's
 * borrowed report. Empty slot succeeds.
 * # Safety
 * Slot holds a unique owned report from a getter/clone or null; aligned independent
 * writable storage and exclusive access are required. Callback reports are excluded.
 */
uint32_t shiro_rs_iteration_report_release(struct ShiroRsIterationReport **slot);

/**
 * Copy the native phone expansion defaults. Default topology is absent.
 * # Safety
 * Output is independent aligned exclusively writable descriptor storage.
 */
uint32_t shiro_rs_phone_options_default(struct ShiroRsPhoneOptions *output);

/**
 * Expand the original UTF-8 phone text using every native option. Null topology
 * means absent; a byte owner may contain any UTF-8 topology, including empty.
 * # Safety
 * Text and optional topology are live readable byte owners. Options are aligned
 * initialized readable storage. Output is independent aligned writable storage
 * holding no live owner on success. Failed output slots remain unchanged.
 */
uint32_t shiro_rs_phone_map_create(const struct ShiroRsBytes *text,
                                   const struct ShiroRsPhoneOptions *options,
                                   const struct ShiroRsBytes *topology,
                                   struct ShiroRsPhoneMap **output);

/**
 * Read the complete original JSON phone map, retaining all additional attributes.
 * # Safety
 * Input is a live readable byte owner; output is independent aligned writable
 * storage holding no live owner on success. Failed output remains unchanged.
 */
uint32_t shiro_rs_phone_map_read_json(const struct ShiroRsBytes *bytes,
                                      struct ShiroRsPhoneMap **output);

/**
 * Write the complete original JSON map into independent byte storage.
 * # Safety
 * Input is a live readable map owner; output is independent aligned writable
 * storage holding no live owner on success. Failed output remains unchanged.
 */
uint32_t shiro_rs_phone_map_write_json(const struct ShiroRsPhoneMap *map,
                                       struct ShiroRsBytes **output);

/**
 * Deep-copy every phone, state and additional JSON attribute.
 * # Safety
 * Input is a live readable map owner; output is independent aligned writable
 * storage holding no live owner on success. Failed output remains unchanged.
 */
uint32_t shiro_rs_phone_map_clone(const struct ShiroRsPhoneMap *map,
                                  struct ShiroRsPhoneMap **output);

/**
 * Release a unique map and clear its slot; an empty slot succeeds.
 * # Safety
 * Slot is independent aligned writable storage holding a unique live map owner
 * or null. Release requires exclusive access and transfers ownership.
 */
uint32_t shiro_rs_phone_map_release(struct ShiroRsPhoneMap **slot);

/**
 * Convert the complete map into original model-definition JSON using native
 * state counts and deterministic tied-duration constraint intersections.
 * # Safety
 * Input is a live readable map owner; output is independent aligned writable
 * storage holding no live owner on success. Failed output remains unchanged.
 */
uint32_t shiro_rs_phone_map_to_definition(const struct ShiroRsPhoneMap *map,
                                          uintptr_t dimensions,
                                          double hop,
                                          struct ShiroRsBytes **output);

/**
 * Generate all initial states from an ordered JSON array of UTF-8 phone names.
 * Preserve native topology, skip edges, binary64 rounding and state metadata.
 * # Safety
 * Inputs are live readable owners; output is independent aligned writable
 * storage holding no live owner on success. Failed output remains unchanged.
 */
uint32_t shiro_rs_segmentation_initial(const struct ShiroRsBytes *names,
                                       const struct ShiroRsPhoneMap *map,
                                       uintptr_t frames,
                                       struct ShiroRsStates **output);

/**
 * Copy all caller labels, preserving every time bit and full UTF-8 name.
 * Each native transformation retains its own validation; construction does not
 * reject intervals that native Label itself can represent.
 * # Safety
 * Inputs are aligned initialized readable descriptors and live readable names.
 * Output is independent aligned writable storage holding no live owner on
 * success. Inputs and failed output slots remain unchanged.
 */
uint32_t shiro_rs_labels_create(const struct ShiroRsLabelInput *values,
                                uintptr_t count,
                                struct ShiroRsLabels **output);

/**
 * Retrieve the complete ordered label count.
 * # Safety
 * Input is a live readable owner; output is independent aligned writable storage.
 */
uint32_t shiro_rs_labels_length(const struct ShiroRsLabels *labels, uintptr_t *output);

/**
 * Copy both binary64 time fields of a label. Invalid index retains output.
 * # Safety
 * Input is a live readable owner; output is independent aligned writable storage.
 */
uint32_t shiro_rs_labels_get_info(const struct ShiroRsLabels *labels,
                                  uintptr_t index,
                                  struct ShiroRsLabelInfo *output);

/**
 * Copy the complete UTF-8 name into an independent byte owner.
 * # Safety
 * Input is a live readable owner; output is independent aligned writable
 * storage holding no live owner on success. Failed output remains unchanged.
 */
uint32_t shiro_rs_labels_get_name(const struct ShiroRsLabels *labels,
                                  uintptr_t index,
                                  struct ShiroRsBytes **output);

/**
 * Deep-copy every label, time bit and name.
 * # Safety
 * Input is a live readable owner; output is independent aligned writable
 * storage holding no live owner on success. Failed output remains unchanged.
 */
uint32_t shiro_rs_labels_clone(const struct ShiroRsLabels *labels, struct ShiroRsLabels **output);

/**
 * Release a unique owner and clear its slot; an empty slot succeeds.
 * # Safety
 * Slot is independent aligned writable storage holding a unique live label owner
 * or null. Release requires exclusive access and transfers ownership.
 */
uint32_t shiro_rs_labels_release(struct ShiroRsLabels **slot);

/**
 * Parse UTF-8 text with the unchanged native tab/space and blank-row semantics.
 * # Safety
 * Input is a live readable byte owner; output is independent aligned writable
 * storage holding no live owner on success. Failed output remains unchanged.
 */
uint32_t shiro_rs_labels_parse(const struct ShiroRsBytes *text, struct ShiroRsLabels **output);

/**
 * Convert complete labels and phone map into all native states, retaining native
 * binary64 boundary arithmetic and state metadata.
 * # Safety
 * Inputs are live readable owners; output is independent aligned writable
 * storage holding no live owner on success. Failed output remains unchanged.
 */
uint32_t shiro_rs_labels_to_states(const struct ShiroRsLabels *labels,
                                   const struct ShiroRsPhoneMap *map,
                                   double hop,
                                   struct ShiroRsStates **output);

/**
 * Convert all states into original phone grouping, optionally interleaving state
 * rows. include_states must be zero or one; hop retains native validation.
 * # Safety
 * Input is a live readable owner; output is independent aligned writable
 * storage holding no live owner on success. Failed output remains unchanged.
 */
uint32_t shiro_rs_labels_from_states(const struct ShiroRsStates *states,
                                     double hop,
                                     uint32_t include_states,
                                     struct ShiroRsLabels **output);

/**
 * Write every label using native round-trip decimals and CRLF endings.
 * Invalid names retain output; no partial buffer is published on failure.
 * # Safety
 * Input is a live readable owner; output is independent aligned writable
 * storage holding no live owner on success. Failed output remains unchanged.
 */
uint32_t shiro_rs_labels_write_bytes(const struct ShiroRsLabels *labels,
                                     struct ShiroRsBytes **output);

/**
 * Compute the original label output path, preserving both legacy separators,
 * leading-dot extension behavior and the literal suffix.
 * # Safety
 * Inputs are live readable UTF-8 byte owners; output is independent aligned
 * writable storage holding no live owner on success. Failed output unchanged.
 */
uint32_t shiro_rs_labels_output_path(const struct ShiroRsBytes *filename,
                                     const struct ShiroRsBytes *suffix,
                                     struct ShiroRsBytes **output);

/**
 * Construct all public native result fields without narrowing them to successful
 * untying results. Assignment validity is checked by native summary generation.
 * # Safety
 * Owners and assignment descriptors are live aligned initialized readable
 * storage. Output is independent aligned writable storage holding no live owner
 * on success. Inputs and failed output slots remain unchanged.
 */
uint32_t shiro_rs_untied_model_create(const struct ShiroRsModel *model,
                                      const struct ShiroRsBytes *document,
                                      const struct ShiroRsAssignment *assignments,
                                      uintptr_t count,
                                      struct ShiroRsUntiedModel **output);

/**
 * Clone distributions in original file/state order, preserving every document
 * attribute and stream weight. Observation files are not opened.
 * # Safety
 * Inputs are live readable owners; output is independent aligned writable
 * storage holding no live owner on success. Failed output remains unchanged.
 */
uint32_t shiro_rs_untie(const struct ShiroRsModel *model,
                        const struct ShiroRsBytes *document,
                        struct ShiroRsUntiedModel **output);

/**
 * Snapshot every model parameter into independent ownership.
 * # Safety
 * Input is a live readable owner; output is independent aligned writable
 * storage holding no live owner on success. Failed output remains unchanged.
 */
uint32_t shiro_rs_untied_model_get_model(const struct ShiroRsUntiedModel *owner,
                                         struct ShiroRsModel **output);

/**
 * Snapshot the complete original segmentation document as JSON bytes.
 * # Safety
 * Input is a live readable owner; output is independent aligned writable
 * storage holding no live owner on success. Failed output remains unchanged.
 */
uint32_t shiro_rs_untied_model_get_document(const struct ShiroRsUntiedModel *owner,
                                            struct ShiroRsBytes **output);

/**
 * Retrieve the complete ordered assignment count.
 * # Safety
 * Input is a live readable owner; output is independent aligned writable storage.
 */
uint32_t shiro_rs_untied_model_length(const struct ShiroRsUntiedModel *owner, uintptr_t *output);

/**
 * Copy all target-width fields of an ordered assignment.
 * # Safety
 * Input is a live readable owner; output is independent aligned writable storage.
 * Invalid index retains output.
 */
uint32_t shiro_rs_untied_model_get_assignment(const struct ShiroRsUntiedModel *owner,
                                              uintptr_t index,
                                              struct ShiroRsAssignment *output);

/**
 * Write the complete native summary into independent bytes. Native validation
 * covers all rows before output; invalid assignments/metadata retain output.
 * # Safety
 * Input is a live readable owner; output is independent aligned writable
 * storage holding no live owner on success. Failed output remains unchanged.
 */
uint32_t shiro_rs_untied_model_summary_bytes(const struct ShiroRsUntiedModel *owner,
                                             struct ShiroRsBytes **output);

/**
 * Deep-copy the complete model, document and assignments.
 * # Safety
 * Input is a live readable owner; output is independent aligned writable
 * storage holding no live owner on success. Failed output remains unchanged.
 */
uint32_t shiro_rs_untied_model_clone(const struct ShiroRsUntiedModel *owner,
                                     struct ShiroRsUntiedModel **output);

/**
 * Release a unique owner and clear its slot; an empty slot succeeds.
 * # Safety
 * Slot is independent aligned writable storage holding a unique live owner or
 * null. Release requires exclusive access and transfers ownership.
 */
uint32_t shiro_rs_untied_model_release(struct ShiroRsUntiedModel **slot);

/**
 * Construct arbitrary complete public native group fields in caller order.
 * Empty collections and repeated input owners are permitted.
 * # Safety
 * Inputs are aligned initialized readable descriptors and live readable owners.
 * Output is independent aligned writable storage holding no live owner on
 * success. Inputs and failed outputs remain unchanged.
 */
uint32_t shiro_rs_isolated_groups_create(const struct ShiroRsIsolatedGroupInput *groups,
                                         uintptr_t count,
                                         struct ShiroRsIsolatedGroups **output);

/**
 * Split using native phone identity, boundary capping and local jump filtering.
 * Preserve all groups, original positions, observation bits and state metadata.
 * # Safety
 * Inputs are live readable owners; output is independent aligned writable
 * storage holding no live owner on success. Failed outputs remain unchanged.
 */
uint32_t shiro_rs_isolated_groups(const struct ShiroRsModel *model,
                                  const struct ShiroRsObservation *observation,
                                  const struct ShiroRsStates *states,
                                  struct ShiroRsIsolatedGroups **output);

/**
 * Retrieve the ordered group count.
 * # Safety
 * Input is a live readable owner; output is independent aligned writable storage.
 */
uint32_t shiro_rs_isolated_groups_length(const struct ShiroRsIsolatedGroups *groups,
                                         uintptr_t *output);

/**
 * Copy both original position fields; an invalid index retains output.
 * # Safety
 * Input is a live readable owner; output is independent aligned writable storage.
 */
uint32_t shiro_rs_isolated_groups_get_info(const struct ShiroRsIsolatedGroups *groups,
                                           uintptr_t index,
                                           struct ShiroRsIsolatedGroupInfo *output);

/**
 * Snapshot the complete observation into independent ownership.
 * # Safety
 * Input is a live readable owner; output is independent aligned writable storage
 * holding no live owner on success. Failed outputs remain unchanged.
 */
uint32_t shiro_rs_isolated_groups_get_observation(const struct ShiroRsIsolatedGroups *groups,
                                                  uintptr_t index,
                                                  struct ShiroRsObservation **output);

/**
 * Snapshot all states, including local times, jumps and extra metadata.
 * # Safety
 * Input is a live readable owner; output is independent aligned writable storage
 * holding no live owner on success. Failed outputs remain unchanged.
 */
uint32_t shiro_rs_isolated_groups_get_states(const struct ShiroRsIsolatedGroups *groups,
                                             uintptr_t index,
                                             struct ShiroRsStates **output);

/**
 * Deep-copy every original position, complete observation and full state sequence.
 * # Safety
 * Input is a live readable owner; output is independent aligned writable storage
 * holding no live owner on success. Failed outputs remain unchanged.
 */
uint32_t shiro_rs_isolated_groups_clone(const struct ShiroRsIsolatedGroups *groups,
                                        struct ShiroRsIsolatedGroups **output);

/**
 * Release a unique owner and clear its slot; an empty slot succeeds.
 * # Safety
 * Slot is independent aligned writable storage holding a unique live owner or
 * null. Release requires exclusive access and transfers ownership.
 */
uint32_t shiro_rs_isolated_groups_release(struct ShiroRsIsolatedGroups **slot);

/**
 * Copy every integer without narrowing or restricting its value.
 * # Safety
 * Input is aligned initialized readable storage for the stated count; empty
 * input permits null. Output is independent aligned writable storage holding
 * no live owner on success. Failed output remains unchanged.
 */
uint32_t shiro_rs_array_usize_create(const uintptr_t *values,
                                     uintptr_t count,
                                     struct ShiroRsArrayUsize **output);

/**
 * Retrieve the complete ordered value count.
 * # Safety
 * Input is a live readable owner and output independent aligned writable storage.
 */
uint32_t shiro_rs_array_usize_length(const struct ShiroRsArrayUsize *values, uintptr_t *output);

/**
 * Copy a complete checked range, retaining the output buffer on failure.
 * # Safety
 * Input is a live readable owner; output is independent aligned writable
 * storage for the stated count and must not alias input. Empty output permits
 * null. Neither participating owner nor storage may be mutated concurrently.
 */
uint32_t shiro_rs_array_usize_copy(const struct ShiroRsArrayUsize *values,
                                   uintptr_t offset,
                                   uintptr_t *output,
                                   uintptr_t count);

/**
 * Deep-copy all integers into an owner independent of the source lifetime.
 * # Safety
 * Input is a live readable owner; output is independent aligned writable
 * storage holding no live owner on success. Failed output remains unchanged.
 */
uint32_t shiro_rs_array_usize_clone(const struct ShiroRsArrayUsize *values,
                                    struct ShiroRsArrayUsize **output);

/**
 * Release unique ownership and clear the slot; an empty slot succeeds.
 * # Safety
 * Slot is independent aligned writable storage holding a unique live owner
 * or null. Release requires exclusive access and transfers ownership.
 */
uint32_t shiro_rs_array_usize_release(struct ShiroRsArrayUsize **slot);

/**
 * Retrieve every model stream dimension in original order with native validation.
 * # Safety
 * Model is a live readable owner; output is independent aligned writable
 * storage holding no live owner on success. Failed output remains unchanged.
 */
uint32_t shiro_rs_model_dimensions(const struct ShiroRsModel *model,
                                   struct ShiroRsArrayUsize **output);

#endif  /* SHIRO_RS_H */
