#ifndef SHIRO_RS_H
#define SHIRO_RS_H

/* Generated by cbindgen. Do not edit manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * Independent owned f32 values; retrieve data through checked copies.
 */
typedef struct ShiroRsArrayF32 ShiroRsArrayF32;

/**
 * Independent owned u8 values; retrieve data through checked copies.
 */
typedef struct ShiroRsBytes ShiroRsBytes;

/**
 * Independent complete native model, including every stream and duration field.
 */
typedef struct ShiroRsModel ShiroRsModel;

/**
 * First revision of SHIRO's additive C interface.
 */
uint32_t shiro_rs_abi_version(void);

/**
 * Copy caller values into an independent owner, retaining all scalar bits.
 * # Safety
 * Borrowed buffers are aligned initialized storage valid for their stated
 * lengths. Owners have the declared type and remain live for the call. Outputs
 * are independent aligned writable storage; constructors use slots holding no
 * live owner. No buffer aliases participating owners. Mutation and release
 * require exclusive access; release transfers unique ownership and clears the
 * initialized slot. Empty buffers permit null pointers.
 */
uint32_t shiro_rs_bytes_create(const uint8_t *data, uintptr_t count, struct ShiroRsBytes **output);

/**
 * Copy the value count; errors retain the initialized output.
 * # Safety
 * Borrowed buffers are aligned initialized storage valid for their stated
 * lengths. Owners have the declared type and remain live for the call. Outputs
 * are independent aligned writable storage; constructors use slots holding no
 * live owner. No buffer aliases participating owners. Mutation and release
 * require exclusive access; release transfers unique ownership and clears the
 * initialized slot. Empty buffers permit null pointers.
 */
uint32_t shiro_rs_bytes_length(const struct ShiroRsBytes *handle, uintptr_t *output);

/**
 * Copy a checked contiguous range; errors leave caller buffers unchanged.
 * # Safety
 * Borrowed buffers are aligned initialized storage valid for their stated
 * lengths. Owners have the declared type and remain live for the call. Outputs
 * are independent aligned writable storage; constructors use slots holding no
 * live owner. No buffer aliases participating owners. Mutation and release
 * require exclusive access; release transfers unique ownership and clears the
 * initialized slot. Empty buffers permit null pointers.
 */
uint32_t shiro_rs_bytes_copy(const struct ShiroRsBytes *handle,
                             uintptr_t offset,
                             uint8_t *output,
                             uintptr_t count);

/**
 * Deep-copy all values; the copy outlives the source owner.
 * # Safety
 * Borrowed buffers are aligned initialized storage valid for their stated
 * lengths. Owners have the declared type and remain live for the call. Outputs
 * are independent aligned writable storage; constructors use slots holding no
 * live owner. No buffer aliases participating owners. Mutation and release
 * require exclusive access; release transfers unique ownership and clears the
 * initialized slot. Empty buffers permit null pointers.
 */
uint32_t shiro_rs_bytes_clone(const struct ShiroRsBytes *handle, struct ShiroRsBytes **output);

/**
 * Release unique ownership and clear its initialized slot. A null owned value is allowed.
 * # Safety
 * Borrowed buffers are aligned initialized storage valid for their stated
 * lengths. Owners have the declared type and remain live for the call. Outputs
 * are independent aligned writable storage; constructors use slots holding no
 * live owner. No buffer aliases participating owners. Mutation and release
 * require exclusive access; release transfers unique ownership and clears the
 * initialized slot. Empty buffers permit null pointers.
 */
uint32_t shiro_rs_bytes_release(struct ShiroRsBytes **owner);

/**
 * Copy caller values into an independent owner, retaining all scalar bits.
 * # Safety
 * Borrowed buffers are aligned initialized storage valid for their stated
 * lengths. Owners have the declared type and remain live for the call. Outputs
 * are independent aligned writable storage; constructors use slots holding no
 * live owner. No buffer aliases participating owners. Mutation and release
 * require exclusive access; release transfers unique ownership and clears the
 * initialized slot. Empty buffers permit null pointers.
 */
uint32_t shiro_rs_array_f32_create(const float *data,
                                   uintptr_t count,
                                   struct ShiroRsArrayF32 **output);

/**
 * Copy the value count; errors retain the initialized output.
 * # Safety
 * Borrowed buffers are aligned initialized storage valid for their stated
 * lengths. Owners have the declared type and remain live for the call. Outputs
 * are independent aligned writable storage; constructors use slots holding no
 * live owner. No buffer aliases participating owners. Mutation and release
 * require exclusive access; release transfers unique ownership and clears the
 * initialized slot. Empty buffers permit null pointers.
 */
uint32_t shiro_rs_array_f32_length(const struct ShiroRsArrayF32 *handle, uintptr_t *output);

/**
 * Copy a checked contiguous range; errors leave caller buffers unchanged.
 * # Safety
 * Borrowed buffers are aligned initialized storage valid for their stated
 * lengths. Owners have the declared type and remain live for the call. Outputs
 * are independent aligned writable storage; constructors use slots holding no
 * live owner. No buffer aliases participating owners. Mutation and release
 * require exclusive access; release transfers unique ownership and clears the
 * initialized slot. Empty buffers permit null pointers.
 */
uint32_t shiro_rs_array_f32_copy(const struct ShiroRsArrayF32 *handle,
                                 uintptr_t offset,
                                 float *output,
                                 uintptr_t count);

/**
 * Deep-copy all values; the copy outlives the source owner.
 * # Safety
 * Borrowed buffers are aligned initialized storage valid for their stated
 * lengths. Owners have the declared type and remain live for the call. Outputs
 * are independent aligned writable storage; constructors use slots holding no
 * live owner. No buffer aliases participating owners. Mutation and release
 * require exclusive access; release transfers unique ownership and clears the
 * initialized slot. Empty buffers permit null pointers.
 */
uint32_t shiro_rs_array_f32_clone(const struct ShiroRsArrayF32 *handle,
                                  struct ShiroRsArrayF32 **output);

/**
 * Release unique ownership and clear its initialized slot. A null owned value is allowed.
 * # Safety
 * Borrowed buffers are aligned initialized storage valid for their stated
 * lengths. Owners have the declared type and remain live for the call. Outputs
 * are independent aligned writable storage; constructors use slots holding no
 * live owner. No buffer aliases participating owners. Mutation and release
 * require exclusive access; release transfers unique ownership and clears the
 * initialized slot. Empty buffers permit null pointers.
 */
uint32_t shiro_rs_array_f32_release(struct ShiroRsArrayF32 **owner);

/**
 * Decode the original headerless little-endian binary32 stream with a scalar budget.
 * Partial final scalars and exceeded budgets retain initialized output slots.
 * # Safety
 * Borrowed buffers are aligned initialized storage valid for their stated
 * lengths. Owners have the declared type and remain live for the call. Outputs
 * are independent aligned writable storage; constructors use slots holding no
 * live owner. No buffer aliases participating owners. Mutation and release
 * require exclusive access; release transfers unique ownership and clears the
 * initialized slot. Empty buffers permit null pointers.
 */
uint32_t shiro_rs_rawfloat_read_bytes(const uint8_t *data,
                                      uintptr_t count,
                                      uintptr_t maximum_samples,
                                      struct ShiroRsArrayF32 **output);

/**
 * Encode all binary32 bits into independent original-format bytes.
 * # Safety
 * Borrowed buffers are aligned initialized storage valid for their stated
 * lengths. Owners have the declared type and remain live for the call. Outputs
 * are independent aligned writable storage; constructors use slots holding no
 * live owner. No buffer aliases participating owners. Mutation and release
 * require exclusive access; release transfers unique ownership and clears the
 * initialized slot. Empty buffers permit null pointers.
 */
uint32_t shiro_rs_rawfloat_write_bytes(const struct ShiroRsArrayF32 *handle,
                                       struct ShiroRsBytes **output);

/**
 * Build a model from the original UTF-8 JSON definition and its native defaults.
 * # Safety
 * Inputs are live owners created by this library. The output is independent,
 * aligned writable storage holding no live owner; it remains unchanged on error.
 */
uint32_t shiro_rs_model_from_definition(const struct ShiroRsBytes *definition,
                                        struct ShiroRsModel **output);

/**
 * Read a complete original model, reject trailing bytes and bound array entries.
 * Supports historical models with and without variance-floor fields.
 * # Safety
 * Input is a live owner created by this library. The output is independent,
 * aligned writable storage holding no live owner; it remains unchanged on error.
 */
uint32_t shiro_rs_model_read_bytes(const struct ShiroRsBytes *bytes,
                                   uintptr_t maximum_array_entries,
                                   struct ShiroRsModel **output);

/**
 * Write a complete original model. Encoding 0 includes variance floors; 1 omits
 * them and rejects nonzero floors instead of losing parameters. Other codes fail.
 * # Safety
 * Input is a live readable owner. The output is independent aligned writable
 * storage holding no live owner; it remains unchanged on error.
 */
uint32_t shiro_rs_model_write_bytes(const struct ShiroRsModel *model,
                                    uint32_t encoding,
                                    struct ShiroRsBytes **output);

/**
 * Clone every model parameter into independent storage.
 * # Safety
 * Input is a live readable owner. The output is independent aligned writable
 * storage holding no live owner; it remains unchanged on error.
 */
uint32_t shiro_rs_model_clone(const struct ShiroRsModel *model, struct ShiroRsModel **output);

/**
 * Release a unique model and clear its initialized slot. An empty slot succeeds.
 * # Safety
 * Slot is independent aligned writable storage containing a unique live model
 * from this library or null. No other call may use the model during release.
 */
uint32_t shiro_rs_model_release(struct ShiroRsModel **slot);

#endif  /* SHIRO_RS_H */
