[package]
publish = false
name = "shiro-rs-python"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
repository.workspace = true
description = "Native Python bindings for shiro-rs"

[lib]
crate-type = ["cdylib", "rlib"]
name = "_shiro_rs"

[dependencies]
rand = { version = "0.10.3", default-features = false }
shiro-rs = { path = "../shiro-rs", version = "0.1.0-alpha.1" }
pyo3 = { version = "0.29.3", features = ["multiple-pymethods"] }
serde_json = "1.0.151"

[features]
cross-windows = ["pyo3/generate-import-lib"]
