[build-system]
requires = ["maturin>=1.15,<2"]
build-backend = "maturin"

[project]
readme = "README.md"
name = "shiro-rs"
dynamic = ["version"]
description = "Native Python bindings for shiro-rs"
requires-python = ">=3.11"
license = "GPL-3.0-or-later"
license-files = ["LICENSE"]

[tool.maturin]
bindings = "pyo3"
python-source = "python"
module-name = "shiro_rs._shiro_rs"

[project.urls]
Repository = "https://github.com/Lqm1/shiro-rs"
Issues = "https://github.com/Lqm1/shiro-rs/issues"

[tool.maturin.generate-ci.github]
trusted-publishing = true
publishing-environment = "release"
